export const codigoPaises = [
  { codigo_pais: 13, nombre_pais: "AFGANISTAN" },
  { codigo_pais: 17, nombre_pais: "ALBANIA" },
  { codigo_pais: 23, nombre_pais: "ALEMANIA" },
  { codigo_pais: 26, nombre_pais: "ARMENIA" },
  { codigo_pais: 27, nombre_pais: "ARUBA" },
  { codigo_pais: 29, nombre_pais: "BOSNIA-HERZEGOVINA" },
  { codigo_pais: 31, nombre_pais: "BURKINA FASSO" },
  { codigo_pais: 37, nombre_pais: "ANDORRA" },
  { codigo_pais: 40, nombre_pais: "ANGOLA" },
  { codigo_pais: 41, nombre_pais: "ANGUILLA" },
  { codigo_pais: 43, nombre_pais: "ANTIGUA Y BARBUDA" },
  { codigo_pais: 47, nombre_pais: "ANTILLAS HOLANDESAS" },
  { codigo_pais: 53, nombre_pais: "ARABIA SAUDITA" },
  { codigo_pais: 59, nombre_pais: "ARGELIA" },
  { codigo_pais: 63, nombre_pais: "ARGENTINA" },
  { codigo_pais: 69, nombre_pais: "AUSTRALIA" },
  { codigo_pais: 72, nombre_pais: "AUSTRIA" },
  { codigo_pais: 74, nombre_pais: "AZERBAIJAN" },
  { codigo_pais: 77, nombre_pais: "BAHAMAS" },
  { codigo_pais: 80, nombre_pais: "BAHREIN" },
  { codigo_pais: 81, nombre_pais: "BANGLADESH" },
  { codigo_pais: 83, nombre_pais: "BARBADOS" },
  { codigo_pais: 87, nombre_pais: "BELGICA" },
  { codigo_pais: 88, nombre_pais: "BELICE" },
  { codigo_pais: 90, nombre_pais: "BERMUDAS" },
  { codigo_pais: 91, nombre_pais: "BELARUS" },
  { codigo_pais: 93, nombre_pais: "BIRMANIA (MYANMAR)" },
  { codigo_pais: 97, nombre_pais: "BOLIVIA" },
  { codigo_pais: 101, nombre_pais: "BOTSWANA" },
  { codigo_pais: 105, nombre_pais: "BRASIL" },
  { codigo_pais: 108, nombre_pais: "BRUNEI DARUSSALAM" },
  { codigo_pais: 111, nombre_pais: "BULGARIA" },
  { codigo_pais: 115, nombre_pais: "BURUNDI" },
  { codigo_pais: 119, nombre_pais: "BUTAN" },
  { codigo_pais: 127, nombre_pais: "CABO VERDE" },
  { codigo_pais: 137, nombre_pais: "CAIMAN, ISLAS" },
  { codigo_pais: 141, nombre_pais: "CAMBOYA (KAMPUCHEA)" },
  { codigo_pais: 145, nombre_pais: "CAMERUN, REPUBLICA UNIDA DEL" },
  { codigo_pais: 149, nombre_pais: "CANADA" },
  { codigo_pais: 159, nombre_pais: "SANTA SEDE" },
  { codigo_pais: 165, nombre_pais: "COCOS (KEELING), ISLAS" },
  { codigo_pais: 169, nombre_pais: "COLOMBIA" },
  { codigo_pais: 173, nombre_pais: "COMORAS" },
  { codigo_pais: 177, nombre_pais: "CONGO" },
  { codigo_pais: 183, nombre_pais: "COOK, ISLAS" },
  {
    codigo_pais: 187,
    nombre_pais: "COREA (NORTE), REPUBLICA POPULAR DEMOCRATICA DE",
  },
  { codigo_pais: 190, nombre_pais: "COREA (SUR), REPUBLICA DE" },
  { codigo_pais: 193, nombre_pais: "COSTA DE MARFIL" },
  { codigo_pais: 196, nombre_pais: "COSTA RICA" },
  { codigo_pais: 198, nombre_pais: "CROACIA" },
  { codigo_pais: 199, nombre_pais: "CUBA" },
  { codigo_pais: 203, nombre_pais: "CHAD" },
  { codigo_pais: 211, nombre_pais: "CHILE" },
  { codigo_pais: 215, nombre_pais: "CHINA" },
  { codigo_pais: 218, nombre_pais: "TAIWAN (FORMOSA)" },
  { codigo_pais: 221, nombre_pais: "CHIPRE" },
  { codigo_pais: 229, nombre_pais: "BENIN" },
  { codigo_pais: 232, nombre_pais: "DINAMARCA" },
  { codigo_pais: 235, nombre_pais: "DOMINICA" },
  { codigo_pais: 239, nombre_pais: "ECUADOR" },
  { codigo_pais: 240, nombre_pais: "EGIPTO" },
  { codigo_pais: 242, nombre_pais: "EL SALVADOR" },
  { codigo_pais: 243, nombre_pais: "ERITREA" },
  { codigo_pais: 244, nombre_pais: "EMIRATOS ARABES UNIDOS" },
  { codigo_pais: 245, nombre_pais: "ESPAÑA" },
  { codigo_pais: 246, nombre_pais: "ESLOVAQUIA" },
  { codigo_pais: 247, nombre_pais: "ESLOVENIA" },
  { codigo_pais: 249, nombre_pais: "ESTADOS UNIDOS" },
  { codigo_pais: 251, nombre_pais: "ESTONIA" },
  { codigo_pais: 253, nombre_pais: "ETIOPIA" },
  { codigo_pais: 259, nombre_pais: "FEROE, ISLAS" },
  { codigo_pais: 267, nombre_pais: "FILIPINAS" },
  { codigo_pais: 271, nombre_pais: "FINLANDIA" },
  { codigo_pais: 275, nombre_pais: "FRANCIA" },
  { codigo_pais: 281, nombre_pais: "GABON" },
  { codigo_pais: 285, nombre_pais: "GAMBIA" },
  { codigo_pais: 287, nombre_pais: "GEORGIA" },
  { codigo_pais: 289, nombre_pais: "GHANA" },
  { codigo_pais: 293, nombre_pais: "GIBRALTAR" },
  { codigo_pais: 297, nombre_pais: "GRANADA" },
  { codigo_pais: 301, nombre_pais: "GRECIA" },
  { codigo_pais: 305, nombre_pais: "GROENLANDIA" },
  { codigo_pais: 309, nombre_pais: "GUADALUPE" },
  { codigo_pais: 313, nombre_pais: "GUAM" },
  { codigo_pais: 317, nombre_pais: "GUATEMALA" },
  { codigo_pais: 325, nombre_pais: "GUAYANA FRANCESA" },
  { codigo_pais: 329, nombre_pais: "GUINEA" },
  { codigo_pais: 331, nombre_pais: "GUINEA ECUATORIAL" },
  { codigo_pais: 334, nombre_pais: "GUINEA-BISSAU" },
  { codigo_pais: 337, nombre_pais: "GUYANA" },
  { codigo_pais: 341, nombre_pais: "HAITI" },
  { codigo_pais: 345, nombre_pais: "HONDURAS" },
  { codigo_pais: 351, nombre_pais: "HONG KONG" },
  { codigo_pais: 355, nombre_pais: "HUNGRIA" },
  { codigo_pais: 361, nombre_pais: "INDIA" },
  { codigo_pais: 365, nombre_pais: "INDONESIA" },
  { codigo_pais: 369, nombre_pais: "IRAK" },
  { codigo_pais: 372, nombre_pais: "IRAN, REPUBLICA ISLAMICA DEL" },
  { codigo_pais: 375, nombre_pais: "IRLANDA (EIRE)" },
  { codigo_pais: 379, nombre_pais: "ISLANDIA" },
  { codigo_pais: 383, nombre_pais: "ISRAEL" },
  { codigo_pais: 386, nombre_pais: "ITALIA" },
  { codigo_pais: 391, nombre_pais: "JAMAICA" },
  { codigo_pais: 399, nombre_pais: "JAPON" },
  { codigo_pais: 403, nombre_pais: "JORDANIA" },
  { codigo_pais: 406, nombre_pais: "KAZAJSTAN" },
  { codigo_pais: 410, nombre_pais: "KENIA" },
  { codigo_pais: 411, nombre_pais: "KIRIBATI" },
  { codigo_pais: 412, nombre_pais: "KIRGUIZISTAN" },
  { codigo_pais: 413, nombre_pais: "KUWAIT" },
  { codigo_pais: 420, nombre_pais: "LAOS, REPUBLICA POPULAR DEMOCRATICA DE" },
  { codigo_pais: 426, nombre_pais: "LESOTHO" },
  { codigo_pais: 429, nombre_pais: "LETONIA" },
  { codigo_pais: 431, nombre_pais: "LIBANO" },
  { codigo_pais: 434, nombre_pais: "LIBERIA" },
  { codigo_pais: 438, nombre_pais: "LIBIA (INCLUYE FEZZAN)" },
  { codigo_pais: 440, nombre_pais: "LIECHTENSTEIN" },
  { codigo_pais: 443, nombre_pais: "LITUANIA" },
  { codigo_pais: 445, nombre_pais: "LUXEMBURGO" },
  { codigo_pais: 447, nombre_pais: "MACAO" },
  { codigo_pais: 448, nombre_pais: "MACEDONIA" },
  { codigo_pais: 450, nombre_pais: "MADAGASCAR" },
  { codigo_pais: 455, nombre_pais: "MALAYSIA" },
  { codigo_pais: 458, nombre_pais: "MALAWI" },
  { codigo_pais: 461, nombre_pais: "MALDIVAS" },
  { codigo_pais: 464, nombre_pais: "MALI" },
  { codigo_pais: 467, nombre_pais: "MALTA" },
  { codigo_pais: 469, nombre_pais: "MARIANAS DEL NORTE, ISLAS" },
  { codigo_pais: 472, nombre_pais: "MARSHALL, ISLAS" },
  { codigo_pais: 474, nombre_pais: "MARRUECOS" },
  { codigo_pais: 477, nombre_pais: "MARTINICA" },
  { codigo_pais: 485, nombre_pais: "MAURICIO" },
  { codigo_pais: 488, nombre_pais: "MAURITANIA" },
  { codigo_pais: 493, nombre_pais: "MEXICO" },
  { codigo_pais: 494, nombre_pais: "MICRONESIA, ESTADOS FEDERADOS DE" },
  { codigo_pais: 496, nombre_pais: "MOLDAVIA" },
  { codigo_pais: 497, nombre_pais: "MONGOLIA" },
  { codigo_pais: 498, nombre_pais: "MONACO" },
  { codigo_pais: 501, nombre_pais: "MONSERRAT, ISLA" },
  { codigo_pais: 505, nombre_pais: "MOZAMBIQUE" },
  { codigo_pais: 507, nombre_pais: "NAMIBIA" },
  { codigo_pais: 508, nombre_pais: "NAURU" },
  { codigo_pais: 511, nombre_pais: "NAVIDAD (CHRISTMAS), ISLAS" },
  { codigo_pais: 517, nombre_pais: "NEPAL" },
  { codigo_pais: 521, nombre_pais: "NICARAGUA" },
  { codigo_pais: 525, nombre_pais: "NIGER" },
  { codigo_pais: 528, nombre_pais: "NIGERIA" },
  { codigo_pais: 531, nombre_pais: "NIUE, ISLA" },
  { codigo_pais: 535, nombre_pais: "NORFOLK, ISLA" },
  { codigo_pais: 538, nombre_pais: "NORUEGA" },
  { codigo_pais: 542, nombre_pais: "NUEVA CALEDONIA" },
  { codigo_pais: 545, nombre_pais: "PAPUASIA NUEVA GUINEA" },
  { codigo_pais: 548, nombre_pais: "NUEVA ZELANDIA" },
  { codigo_pais: 551, nombre_pais: "VANUATU" },
  { codigo_pais: 556, nombre_pais: "OMAN" },
  { codigo_pais: 566, nombre_pais: "PACIFICO, ISLAS (USA)" },
  { codigo_pais: 573, nombre_pais: "PAISES BAJOS (HOLANDA)" },
  { codigo_pais: 576, nombre_pais: "PAKISTAN" },
  { codigo_pais: 578, nombre_pais: "PALAU, ISLAS" },
  { codigo_pais: 580, nombre_pais: "PANAMA" },
  { codigo_pais: 586, nombre_pais: "PARAGUAY" },
  { codigo_pais: 589, nombre_pais: "PERU" },
  { codigo_pais: 593, nombre_pais: "PITCAIRN, ISLA" },
  { codigo_pais: 599, nombre_pais: "POLINESIA FRANCESA" },
  { codigo_pais: 603, nombre_pais: "POLONIA" },
  { codigo_pais: 607, nombre_pais: "PORTUGAL" },
  { codigo_pais: 611, nombre_pais: "PUERTO RICO" },
  { codigo_pais: 618, nombre_pais: "QATAR" },
  { codigo_pais: 628, nombre_pais: "REINO UNIDO" },
  { codigo_pais: 640, nombre_pais: "REPUBLICA CENTROAFRICANA" },
  { codigo_pais: 644, nombre_pais: "REPUBLICA CHECA" },
  { codigo_pais: 647, nombre_pais: "REPUBLICA DOMINICANA" },
  { codigo_pais: 660, nombre_pais: "REUNION" },
  { codigo_pais: 665, nombre_pais: "ZIMBABWE" },
  { codigo_pais: 670, nombre_pais: "RUMANIA" },
  { codigo_pais: 675, nombre_pais: "RUANDA" },
  { codigo_pais: 676, nombre_pais: "RUSIA" },
  { codigo_pais: 677, nombre_pais: "SALOMON, ISLAS" },
  { codigo_pais: 685, nombre_pais: "SAHARA OCCIDENTAL" },
  { codigo_pais: 687, nombre_pais: "SAMOA" },
  { codigo_pais: 690, nombre_pais: "SAMOA NORTEAMERICANA" },
  { codigo_pais: 695, nombre_pais: "SAN CRISTOBAL Y NIEVES" },
  { codigo_pais: 697, nombre_pais: "SAN MARINO" },
  { codigo_pais: 700, nombre_pais: "SAN PEDRO Y MIGUELON" },
  { codigo_pais: 705, nombre_pais: "SAN VICENTE Y LAS GRANADINAS" },
  { codigo_pais: 710, nombre_pais: "SANTA ELENA" },
  { codigo_pais: 715, nombre_pais: "SANTA LUCIA" },
  { codigo_pais: 720, nombre_pais: "SANTO TOME Y PRINCIPE" },
  { codigo_pais: 728, nombre_pais: "SENEGAL" },
  { codigo_pais: 731, nombre_pais: "SEYCHELLES" },
  { codigo_pais: 735, nombre_pais: "SIERRA LEONA" },
  { codigo_pais: 741, nombre_pais: "SINGAPUR" },
  { codigo_pais: 744, nombre_pais: "SIRIA, REPUBLICA ARABE DE" },
  { codigo_pais: 748, nombre_pais: "SOMALIA" },
  { codigo_pais: 750, nombre_pais: "SRI LANKA" },
  { codigo_pais: 756, nombre_pais: "SUDAFRICA, REPUBLICA DE" },
  { codigo_pais: 759, nombre_pais: "SUDAN" },
  { codigo_pais: 764, nombre_pais: "SUECIA" },
  { codigo_pais: 767, nombre_pais: "SUIZA" },
  { codigo_pais: 770, nombre_pais: "SURINAM" },
  { codigo_pais: 773, nombre_pais: "SWAZILANDIA" },
  { codigo_pais: 774, nombre_pais: "TADJIKISTAN" },
  { codigo_pais: 776, nombre_pais: "TAILANDIA" },
  { codigo_pais: 780, nombre_pais: "TANZANIA, REPUBLICA UNIDA DE" },
  { codigo_pais: 783, nombre_pais: "DJIBOUTI" },
  { codigo_pais: 787, nombre_pais: "TERRITORIO BRITANICO DEL OCEANO INDICO" },
];