export const codigoDepartamentos = [
  {
    codigo_departamento: 5,
    nombre_departamento: "ANTIOQUIA",
    codigo_pais: 169,
  },
  {
    codigo_departamento: 8,
    nombre_departamento: "ATLANTICO",
    codigo_pais: 169,
  },
  {
    codigo_departamento: 11,
    nombre_departamento: "BOGOTA. D.C.",
    codigo_pais: 169,
  },
  { codigo_departamento: 13, nombre_departamento: "BOLIVAR", codigo_pais: 169 },
  { codigo_departamento: 15, nombre_departamento: "BOYACA", codigo_pais: 169 },
  { codigo_departamento: 19, nombre_departamento: "CAUCA", codigo_pais: 169 },
  { codigo_departamento: 17, nombre_departamento: "CALDAS", codigo_pais: 169 },
  { codigo_departamento: 18, nombre_departamento: "CAQUETA", codigo_pais: 169 },
  { codigo_departamento: 20, nombre_departamento: "CESAR", codigo_pais: 169 },
  { codigo_departamento: 23, nombre_departamento: "CORDOBA", codigo_pais: 169 },
  {
    codigo_departamento: 25,
    nombre_departamento: "CUNDINAMARCA",
    codigo_pais: 169,
  },
  { codigo_departamento: 27, nombre_departamento: "CHOCO", codigo_pais: 169 },
  { codigo_departamento: 41, nombre_departamento: "HUILA", codigo_pais: 169 },
  {
    codigo_departamento: 44,
    nombre_departamento: "LA GUAJIRA",
    codigo_pais: 169,
  },
  {
    codigo_departamento: 47,
    nombre_departamento: "MAGDALENA",
    codigo_pais: 169,
  },
  { codigo_departamento: 50, nombre_departamento: "META", codigo_pais: 169 },
  { codigo_departamento: 52, nombre_departamento: "NARIÑO", codigo_pais: 169 },
  {
    codigo_departamento: 54,
    nombre_departamento: "NORTE DE SANTANDER",
    codigo_pais: 169,
  },
  { codigo_departamento: 63, nombre_departamento: "QUINDIO", codigo_pais: 169 },
  {
    codigo_departamento: 66,
    nombre_departamento: "RISARALDA",
    codigo_pais: 169,
  },
  {
    codigo_departamento: 68,
    nombre_departamento: "SANTANDER",
    codigo_pais: 169,
  },
  { codigo_departamento: 70, nombre_departamento: "SUCRE", codigo_pais: 169 },
  { codigo_departamento: 73, nombre_departamento: "TOLIMA", codigo_pais: 169 },
  {
    codigo_departamento: 76,
    nombre_departamento: "VALLE DEL CAUCA",
    codigo_pais: 169,
  },
  { codigo_departamento: 81, nombre_departamento: "ARAUCA", codigo_pais: 169 },
  {
    codigo_departamento: 85,
    nombre_departamento: "CASANARE",
    codigo_pais: 169,
  },
  {
    codigo_departamento: 86,
    nombre_departamento: "PUTUMAYO",
    codigo_pais: 169,
  },
  {
    codigo_departamento: 88,
    nombre_departamento:
      "ARCHIPIELAGO DE SAN ANDRES. PROVIDENCIA Y SANTA CATALINA",
    codigo_pais: 169,
  },
  {
    codigo_departamento: 91,
    nombre_departamento: "AMAZONAS",
    codigo_pais: 169,
  },
  { codigo_departamento: 94, nombre_departamento: "GUAINIA", codigo_pais: 169 },
  {
    codigo_departamento: 95,
    nombre_departamento: "GUAVIARE",
    codigo_pais: 169,
  },
  { codigo_departamento: 97, nombre_departamento: "VAUPES", codigo_pais: 169 },
  { codigo_departamento: 99, nombre_departamento: "VICHADA", codigo_pais: 169 },
];
