export const codigoCiudades = [
  { codigo_ciudad: 5001, nombre_ciudad: "MEDELLIN", codigo_departamento: 5 },
  { codigo_ciudad: 5002, nombre_ciudad: "ABEJORRAL", codigo_departamento: 5 },
  { codigo_ciudad: 5004, nombre_ciudad: "ABRIAQUI", codigo_departamento: 5 },
  { codigo_ciudad: 5021, nombre_ciudad: "ALEJANDRIA", codigo_departamento: 5 },
  { codigo_ciudad: 5030, nombre_ciudad: "AMAGA", codigo_departamento: 5 },
  { codigo_ciudad: 5031, nombre_ciudad: "AMALFI", codigo_departamento: 5 },
  { codigo_ciudad: 5034, nombre_ciudad: "ANDES", codigo_departamento: 5 },
  { codigo_ciudad: 5036, nombre_ciudad: "ANGELOPOLIS", codigo_departamento: 5 },
  { codigo_ciudad: 5038, nombre_ciudad: "ANGOSTURA", codigo_departamento: 5 },
  { codigo_ciudad: 5040, nombre_ciudad: "ANORI", codigo_departamento: 5 },
  {
    codigo_ciudad: 5042,
    nombre_ciudad: "SANTA FE DE ANTIOQUIA",
    codigo_departamento: 5,
  },
  { codigo_ciudad: 5044, nombre_ciudad: "ANZA", codigo_departamento: 5 },
  { codigo_ciudad: 5045, nombre_ciudad: "APARTADO", codigo_departamento: 5 },
  { codigo_ciudad: 5051, nombre_ciudad: "ARBOLETES", codigo_departamento: 5 },
  { codigo_ciudad: 5055, nombre_ciudad: "ARGELIA", codigo_departamento: 5 },
  { codigo_ciudad: 5059, nombre_ciudad: "ARMENIA", codigo_departamento: 5 },
  { codigo_ciudad: 5079, nombre_ciudad: "BARBOSA", codigo_departamento: 5 },
  { codigo_ciudad: 5086, nombre_ciudad: "BELMIRA", codigo_departamento: 5 },
  { codigo_ciudad: 5088, nombre_ciudad: "BELLO", codigo_departamento: 5 },
  { codigo_ciudad: 5091, nombre_ciudad: "BETANIA", codigo_departamento: 5 },
  { codigo_ciudad: 5093, nombre_ciudad: "BETULIA", codigo_departamento: 5 },
  {
    codigo_ciudad: 5101,
    nombre_ciudad: "CIUDAD BOLIVAR",
    codigo_departamento: 5,
  },
  { codigo_ciudad: 5107, nombre_ciudad: "BRICEÑO", codigo_departamento: 5 },
  { codigo_ciudad: 5113, nombre_ciudad: "BURITICA", codigo_departamento: 5 },
  { codigo_ciudad: 5120, nombre_ciudad: "CACERES", codigo_departamento: 5 },
  { codigo_ciudad: 5125, nombre_ciudad: "CAICEDO", codigo_departamento: 5 },
  { codigo_ciudad: 5129, nombre_ciudad: "CALDAS", codigo_departamento: 5 },
  { codigo_ciudad: 5134, nombre_ciudad: "CAMPAMENTO", codigo_departamento: 5 },
  { codigo_ciudad: 5138, nombre_ciudad: "CAÑASGORDAS", codigo_departamento: 5 },
  { codigo_ciudad: 5142, nombre_ciudad: "CARACOLI", codigo_departamento: 5 },
  { codigo_ciudad: 5145, nombre_ciudad: "CARAMANTA", codigo_departamento: 5 },
  { codigo_ciudad: 5147, nombre_ciudad: "CAREPA", codigo_departamento: 5 },
  {
    codigo_ciudad: 5148,
    nombre_ciudad: "EL CARMEN DE VIBORAL",
    codigo_departamento: 5,
  },
  { codigo_ciudad: 5150, nombre_ciudad: "CAROLINA", codigo_departamento: 5 },
  { codigo_ciudad: 5154, nombre_ciudad: "CAUCASIA", codigo_departamento: 5 },
  { codigo_ciudad: 5172, nombre_ciudad: "CHIGORODO", codigo_departamento: 5 },
  { codigo_ciudad: 5190, nombre_ciudad: "CISNEROS", codigo_departamento: 5 },
  { codigo_ciudad: 5197, nombre_ciudad: "COCORNA", codigo_departamento: 5 },
  { codigo_ciudad: 5206, nombre_ciudad: "CONCEPCION", codigo_departamento: 5 },
  { codigo_ciudad: 5209, nombre_ciudad: "CONCORDIA", codigo_departamento: 5 },
  { codigo_ciudad: 5212, nombre_ciudad: "COPACABANA", codigo_departamento: 5 },
  { codigo_ciudad: 5234, nombre_ciudad: "DABEIBA", codigo_departamento: 5 },
  { codigo_ciudad: 5237, nombre_ciudad: "DONMATIAS", codigo_departamento: 5 },
  { codigo_ciudad: 5240, nombre_ciudad: "EBEJICO", codigo_departamento: 5 },
  { codigo_ciudad: 5250, nombre_ciudad: "EL BAGRE", codigo_departamento: 5 },
  { codigo_ciudad: 5264, nombre_ciudad: "ENTRERRIOS", codigo_departamento: 5 },
  { codigo_ciudad: 5266, nombre_ciudad: "ENVIGADO", codigo_departamento: 5 },
  { codigo_ciudad: 5282, nombre_ciudad: "FREDONIA", codigo_departamento: 5 },
  { codigo_ciudad: 5284, nombre_ciudad: "FRONTINO", codigo_departamento: 5 },
  { codigo_ciudad: 5306, nombre_ciudad: "GIRALDO", codigo_departamento: 5 },
  { codigo_ciudad: 5308, nombre_ciudad: "GIRARDOTA", codigo_departamento: 5 },
  { codigo_ciudad: 5310, nombre_ciudad: "GOMEZ PLATA", codigo_departamento: 5 },
  { codigo_ciudad: 5313, nombre_ciudad: "GRANADA", codigo_departamento: 5 },
  { codigo_ciudad: 5315, nombre_ciudad: "GUADALUPE", codigo_departamento: 5 },
  { codigo_ciudad: 5318, nombre_ciudad: "GUARNE", codigo_departamento: 5 },
  { codigo_ciudad: 5321, nombre_ciudad: "GUATAPE", codigo_departamento: 5 },
  { codigo_ciudad: 5347, nombre_ciudad: "HELICONIA", codigo_departamento: 5 },
  { codigo_ciudad: 5353, nombre_ciudad: "HISPANIA", codigo_departamento: 5 },
  { codigo_ciudad: 5360, nombre_ciudad: "ITAGÜI", codigo_departamento: 5 },
  { codigo_ciudad: 5361, nombre_ciudad: "ITUANGO", codigo_departamento: 5 },
  { codigo_ciudad: 5364, nombre_ciudad: "JARDIN", codigo_departamento: 5 },
  { codigo_ciudad: 5368, nombre_ciudad: "JERICO", codigo_departamento: 5 },
  { codigo_ciudad: 5376, nombre_ciudad: "LA CEJA", codigo_departamento: 5 },
  { codigo_ciudad: 5380, nombre_ciudad: "LA ESTRELLA", codigo_departamento: 5 },
  { codigo_ciudad: 5390, nombre_ciudad: "LA PINTADA", codigo_departamento: 5 },
  { codigo_ciudad: 5400, nombre_ciudad: "LA UNION", codigo_departamento: 5 },
  { codigo_ciudad: 5411, nombre_ciudad: "LIBORINA", codigo_departamento: 5 },
  { codigo_ciudad: 5425, nombre_ciudad: "MACEO", codigo_departamento: 5 },
  { codigo_ciudad: 5440, nombre_ciudad: "MARINILLA", codigo_departamento: 5 },
  { codigo_ciudad: 5467, nombre_ciudad: "MONTEBELLO", codigo_departamento: 5 },
  { codigo_ciudad: 5475, nombre_ciudad: "MURINDO", codigo_departamento: 5 },
  { codigo_ciudad: 5480, nombre_ciudad: "MUTATA", codigo_departamento: 5 },
  { codigo_ciudad: 5483, nombre_ciudad: "NARIÑO", codigo_departamento: 5 },
  { codigo_ciudad: 5490, nombre_ciudad: "NECOCLI", codigo_departamento: 5 },
  { codigo_ciudad: 5495, nombre_ciudad: "NECHI", codigo_departamento: 5 },
  { codigo_ciudad: 5501, nombre_ciudad: "OLAYA", codigo_departamento: 5 },
  { codigo_ciudad: 5541, nombre_ciudad: "PEÑOL", codigo_departamento: 5 },
  { codigo_ciudad: 5543, nombre_ciudad: "PEQUE", codigo_departamento: 5 },
  { codigo_ciudad: 5576, nombre_ciudad: "PUEBLORRICO", codigo_departamento: 5 },
  {
    codigo_ciudad: 5579,
    nombre_ciudad: "PUERTO BERRIO",
    codigo_departamento: 5,
  },
  { codigo_ciudad: 5585, nombre_ciudad: "PUERTO NARE", codigo_departamento: 5 },
  {
    codigo_ciudad: 5591,
    nombre_ciudad: "PUERTO TRIUNFO",
    codigo_departamento: 5,
  },
  { codigo_ciudad: 5604, nombre_ciudad: "REMEDIOS", codigo_departamento: 5 },
  { codigo_ciudad: 5607, nombre_ciudad: "RETIRO", codigo_departamento: 5 },
  { codigo_ciudad: 5615, nombre_ciudad: "RIONEGRO", codigo_departamento: 5 },
  { codigo_ciudad: 5628, nombre_ciudad: "SABANALARGA", codigo_departamento: 5 },
  { codigo_ciudad: 5631, nombre_ciudad: "SABANETA", codigo_departamento: 5 },
  { codigo_ciudad: 5642, nombre_ciudad: "SALGAR", codigo_departamento: 5 },
  {
    codigo_ciudad: 5647,
    nombre_ciudad: "SAN ANDRES DE CUERQUIA",
    codigo_departamento: 5,
  },
  { codigo_ciudad: 5649, nombre_ciudad: "SAN CARLOS", codigo_departamento: 5 },
  {
    codigo_ciudad: 5652,
    nombre_ciudad: "SAN FRANCISCO",
    codigo_departamento: 5,
  },
  {
    codigo_ciudad: 5656,
    nombre_ciudad: "SAN JERONIMO",
    codigo_departamento: 5,
  },
  {
    codigo_ciudad: 5658,
    nombre_ciudad: "SAN JOSE DE LA MONTAÑA",
    codigo_departamento: 5,
  },
  {
    codigo_ciudad: 5659,
    nombre_ciudad: "SAN JUAN DE URABA",
    codigo_departamento: 5,
  },
  { codigo_ciudad: 5660, nombre_ciudad: "SAN LUIS", codigo_departamento: 5 },
  {
    codigo_ciudad: 5664,
    nombre_ciudad: "SAN PEDRO DE LOS MILAGROS",
    codigo_departamento: 5,
  },
  {
    codigo_ciudad: 5665,
    nombre_ciudad: "SAN PEDRO DE URABA",
    codigo_departamento: 5,
  },
  { codigo_ciudad: 5667, nombre_ciudad: "SAN RAFAEL", codigo_departamento: 5 },
  { codigo_ciudad: 5670, nombre_ciudad: "SAN ROQUE", codigo_departamento: 5 },
  {
    codigo_ciudad: 5674,
    nombre_ciudad: "SAN VICENTE FERRER",
    codigo_departamento: 5,
  },
  {
    codigo_ciudad: 5679,
    nombre_ciudad: "SANTA BARBARA",
    codigo_departamento: 5,
  },
  {
    codigo_ciudad: 5686,
    nombre_ciudad: "SANTA ROSA DE OSOS",
    codigo_departamento: 5,
  },
  {
    codigo_ciudad: 5690,
    nombre_ciudad: "SANTO DOMINGO",
    codigo_departamento: 5,
  },
  {
    codigo_ciudad: 5697,
    nombre_ciudad: "EL SANTUARIO",
    codigo_departamento: 5,
  },
  { codigo_ciudad: 5736, nombre_ciudad: "SEGOVIA", codigo_departamento: 5 },
  { codigo_ciudad: 5756, nombre_ciudad: "SONSON", codigo_departamento: 5 },
  { codigo_ciudad: 5761, nombre_ciudad: "SOPETRAN", codigo_departamento: 5 },
  { codigo_ciudad: 5789, nombre_ciudad: "TAMESIS", codigo_departamento: 5 },
  { codigo_ciudad: 5790, nombre_ciudad: "TARAZA", codigo_departamento: 5 },
  { codigo_ciudad: 5792, nombre_ciudad: "TARSO", codigo_departamento: 5 },
  { codigo_ciudad: 5809, nombre_ciudad: "TITIRIBI", codigo_departamento: 5 },
  { codigo_ciudad: 5819, nombre_ciudad: "TOLEDO", codigo_departamento: 5 },
  { codigo_ciudad: 5837, nombre_ciudad: "TURBO", codigo_departamento: 5 },
  { codigo_ciudad: 5842, nombre_ciudad: "URAMITA", codigo_departamento: 5 },
  { codigo_ciudad: 5847, nombre_ciudad: "URRAO", codigo_departamento: 5 },
  { codigo_ciudad: 5854, nombre_ciudad: "VALDIVIA", codigo_departamento: 5 },
  { codigo_ciudad: 5856, nombre_ciudad: "VALPARAISO", codigo_departamento: 5 },
  { codigo_ciudad: 5858, nombre_ciudad: "VEGACHI", codigo_departamento: 5 },
  { codigo_ciudad: 5861, nombre_ciudad: "VENECIA", codigo_departamento: 5 },
  {
    codigo_ciudad: 5873,
    nombre_ciudad: "VIGIA DEL FUERTE",
    codigo_departamento: 5,
  },
  { codigo_ciudad: 5885, nombre_ciudad: "YALI", codigo_departamento: 5 },
  { codigo_ciudad: 5887, nombre_ciudad: "YARUMAL", codigo_departamento: 5 },
  { codigo_ciudad: 5890, nombre_ciudad: "YOLOMBO", codigo_departamento: 5 },
  { codigo_ciudad: 5893, nombre_ciudad: "YONDO", codigo_departamento: 5 },
  { codigo_ciudad: 5895, nombre_ciudad: "ZARAGOZA", codigo_departamento: 5 },
  {
    codigo_ciudad: 8001,
    nombre_ciudad: "BARRANQUILLA",
    codigo_departamento: 8,
  },
  { codigo_ciudad: 8078, nombre_ciudad: "BARANOA", codigo_departamento: 8 },
  {
    codigo_ciudad: 8137,
    nombre_ciudad: "CAMPO DE LA CRUZ",
    codigo_departamento: 8,
  },
  { codigo_ciudad: 8141, nombre_ciudad: "CANDELARIA", codigo_departamento: 8 },
  { codigo_ciudad: 8296, nombre_ciudad: "GALAPA", codigo_departamento: 8 },
  {
    codigo_ciudad: 8372,
    nombre_ciudad: "JUAN DE ACOSTA",
    codigo_departamento: 8,
  },
  { codigo_ciudad: 8421, nombre_ciudad: "LURUACO", codigo_departamento: 8 },
  { codigo_ciudad: 8433, nombre_ciudad: "MALAMBO", codigo_departamento: 8 },
  { codigo_ciudad: 8436, nombre_ciudad: "MANATI", codigo_departamento: 8 },
  {
    codigo_ciudad: 8520,
    nombre_ciudad: "PALMAR DE VARELA",
    codigo_departamento: 8,
  },
  { codigo_ciudad: 8549, nombre_ciudad: "PIOJO", codigo_departamento: 8 },
  { codigo_ciudad: 8558, nombre_ciudad: "POLONUEVO", codigo_departamento: 8 },
  { codigo_ciudad: 8560, nombre_ciudad: "PONEDERA", codigo_departamento: 8 },
  {
    codigo_ciudad: 8573,
    nombre_ciudad: "PUERTO COLOMBIA",
    codigo_departamento: 8,
  },
  { codigo_ciudad: 8606, nombre_ciudad: "REPELON", codigo_departamento: 8 },
  {
    codigo_ciudad: 8634,
    nombre_ciudad: "SABANAGRANDE",
    codigo_departamento: 8,
  },
  { codigo_ciudad: 8638, nombre_ciudad: "SABANALARGA", codigo_departamento: 8 },
  { codigo_ciudad: 8675, nombre_ciudad: "SANTA LUCIA", codigo_departamento: 8 },
  { codigo_ciudad: 8685, nombre_ciudad: "SANTO TOMAS", codigo_departamento: 8 },
  { codigo_ciudad: 8758, nombre_ciudad: "SOLEDAD", codigo_departamento: 8 },
  { codigo_ciudad: 8770, nombre_ciudad: "SUAN", codigo_departamento: 8 },
  { codigo_ciudad: 8832, nombre_ciudad: "TUBARA", codigo_departamento: 8 },
  { codigo_ciudad: 8849, nombre_ciudad: "USIACURI", codigo_departamento: 8 },
  {
    codigo_ciudad: 11001,
    nombre_ciudad: "BOGOTA. D.C.",
    codigo_departamento: 11,
  },
  {
    codigo_ciudad: 13001,
    nombre_ciudad: "CARTAGENA DE INDIAS",
    codigo_departamento: 13,
  },
  { codigo_ciudad: 13006, nombre_ciudad: "ACHI", codigo_departamento: 13 },
  {
    codigo_ciudad: 13030,
    nombre_ciudad: "ALTOS DEL ROSARIO",
    codigo_departamento: 13,
  },
  { codigo_ciudad: 13042, nombre_ciudad: "ARENAL", codigo_departamento: 13 },
  { codigo_ciudad: 13052, nombre_ciudad: "ARJONA", codigo_departamento: 13 },
  {
    codigo_ciudad: 13062,
    nombre_ciudad: "ARROYOHONDO",
    codigo_departamento: 13,
  },
  {
    codigo_ciudad: 13074,
    nombre_ciudad: "BARRANCO DE LOBA",
    codigo_departamento: 13,
  },
  { codigo_ciudad: 13140, nombre_ciudad: "CALAMAR", codigo_departamento: 13 },
  {
    codigo_ciudad: 13160,
    nombre_ciudad: "CANTAGALLO",
    codigo_departamento: 13,
  },
  { codigo_ciudad: 13188, nombre_ciudad: "CICUCO", codigo_departamento: 13 },
  { codigo_ciudad: 13212, nombre_ciudad: "CORDOBA", codigo_departamento: 13 },
  { codigo_ciudad: 13222, nombre_ciudad: "CLEMENCIA", codigo_departamento: 13 },
  {
    codigo_ciudad: 13244,
    nombre_ciudad: "EL CARMEN DE BOLIVAR",
    codigo_departamento: 13,
  },
  { codigo_ciudad: 13248, nombre_ciudad: "EL GUAMO", codigo_departamento: 13 },
  { codigo_ciudad: 13268, nombre_ciudad: "EL PEÑON", codigo_departamento: 13 },
  {
    codigo_ciudad: 13300,
    nombre_ciudad: "HATILLO DE LOBA",
    codigo_departamento: 13,
  },
  { codigo_ciudad: 13430, nombre_ciudad: "MAGANGUE", codigo_departamento: 13 },
  { codigo_ciudad: 13433, nombre_ciudad: "MAHATES", codigo_departamento: 13 },
  { codigo_ciudad: 13440, nombre_ciudad: "MARGARITA", codigo_departamento: 13 },
  {
    codigo_ciudad: 13442,
    nombre_ciudad: "MARIA LA BAJA",
    codigo_departamento: 13,
  },
  {
    codigo_ciudad: 13458,
    nombre_ciudad: "MONTECRISTO",
    codigo_departamento: 13,
  },
  {
    codigo_ciudad: 13468,
    nombre_ciudad: "SANTA CRUZ DE MOMPOX",
    codigo_departamento: 13,
  },
  { codigo_ciudad: 13473, nombre_ciudad: "MORALES", codigo_departamento: 13 },
  { codigo_ciudad: 13490, nombre_ciudad: "NOROSI", codigo_departamento: 13 },
  { codigo_ciudad: 13549, nombre_ciudad: "PINILLOS", codigo_departamento: 13 },
  { codigo_ciudad: 13580, nombre_ciudad: "REGIDOR", codigo_departamento: 13 },
  { codigo_ciudad: 13600, nombre_ciudad: "RIO VIEJO", codigo_departamento: 13 },
  {
    codigo_ciudad: 13620,
    nombre_ciudad: "SAN CRISTOBAL",
    codigo_departamento: 13,
  },
  {
    codigo_ciudad: 13647,
    nombre_ciudad: "SAN ESTANISLAO",
    codigo_departamento: 13,
  },
  {
    codigo_ciudad: 13650,
    nombre_ciudad: "SAN FERNANDO",
    codigo_departamento: 13,
  },
  {
    codigo_ciudad: 13654,
    nombre_ciudad: "SAN JACINTO",
    codigo_departamento: 13,
  },
  {
    codigo_ciudad: 13655,
    nombre_ciudad: "SAN JACINTO DEL CAUCA",
    codigo_departamento: 13,
  },
  {
    codigo_ciudad: 13657,
    nombre_ciudad: "SAN JUAN NEPOMUCENO",
    codigo_departamento: 13,
  },
  {
    codigo_ciudad: 13667,
    nombre_ciudad: "SAN MARTIN DE LOBA",
    codigo_departamento: 13,
  },
  { codigo_ciudad: 13670, nombre_ciudad: "SAN PABLO", codigo_departamento: 13 },
  {
    codigo_ciudad: 13673,
    nombre_ciudad: "SANTA CATALINA",
    codigo_departamento: 13,
  },
  {
    codigo_ciudad: 13683,
    nombre_ciudad: "SANTA ROSA",
    codigo_departamento: 13,
  },
  {
    codigo_ciudad: 13688,
    nombre_ciudad: "SANTA ROSA DEL SUR",
    codigo_departamento: 13,
  },
  { codigo_ciudad: 13744, nombre_ciudad: "SIMITI", codigo_departamento: 13 },
  {
    codigo_ciudad: 13760,
    nombre_ciudad: "SOPLAVIENTO",
    codigo_departamento: 13,
  },
  {
    codigo_ciudad: 13780,
    nombre_ciudad: "TALAIGUA NUEVO",
    codigo_departamento: 13,
  },
  { codigo_ciudad: 13810, nombre_ciudad: "TIQUISIO", codigo_departamento: 13 },
  { codigo_ciudad: 13836, nombre_ciudad: "TURBACO", codigo_departamento: 13 },
  { codigo_ciudad: 13838, nombre_ciudad: "TURBANA", codigo_departamento: 13 },
  {
    codigo_ciudad: 13873,
    nombre_ciudad: "VILLANUEVA",
    codigo_departamento: 13,
  },
  { codigo_ciudad: 13894, nombre_ciudad: "ZAMBRANO", codigo_departamento: 13 },
  { codigo_ciudad: 15001, nombre_ciudad: "TUNJA", codigo_departamento: 15 },
  { codigo_ciudad: 15022, nombre_ciudad: "ALMEIDA", codigo_departamento: 15 },
  { codigo_ciudad: 15047, nombre_ciudad: "AQUITANIA", codigo_departamento: 15 },
  { codigo_ciudad: 15051, nombre_ciudad: "ARCABUCO", codigo_departamento: 15 },
  { codigo_ciudad: 15087, nombre_ciudad: "BELEN", codigo_departamento: 15 },
  { codigo_ciudad: 15090, nombre_ciudad: "BERBEO", codigo_departamento: 15 },
  { codigo_ciudad: 15092, nombre_ciudad: "BETEITIVA", codigo_departamento: 15 },
  { codigo_ciudad: 15097, nombre_ciudad: "BOAVITA", codigo_departamento: 15 },
  { codigo_ciudad: 15104, nombre_ciudad: "BOYACA", codigo_departamento: 15 },
  { codigo_ciudad: 15106, nombre_ciudad: "BRICEÑO", codigo_departamento: 15 },
  {
    codigo_ciudad: 15109,
    nombre_ciudad: "BUENAVISTA",
    codigo_departamento: 15,
  },
  { codigo_ciudad: 15114, nombre_ciudad: "BUSBANZA", codigo_departamento: 15 },
  { codigo_ciudad: 15131, nombre_ciudad: "CALDAS", codigo_departamento: 15 },
  {
    codigo_ciudad: 15135,
    nombre_ciudad: "CAMPOHERMOSO",
    codigo_departamento: 15,
  },
  { codigo_ciudad: 15162, nombre_ciudad: "CERINZA", codigo_departamento: 15 },
  { codigo_ciudad: 15172, nombre_ciudad: "CHINAVITA", codigo_departamento: 15 },
  {
    codigo_ciudad: 15176,
    nombre_ciudad: "CHIQUINQUIRA",
    codigo_departamento: 15,
  },
  { codigo_ciudad: 15180, nombre_ciudad: "CHISCAS", codigo_departamento: 15 },
  { codigo_ciudad: 15183, nombre_ciudad: "CHITA", codigo_departamento: 15 },
  {
    codigo_ciudad: 15185,
    nombre_ciudad: "CHITARAQUE",
    codigo_departamento: 15,
  },
  { codigo_ciudad: 15187, nombre_ciudad: "CHIVATA", codigo_departamento: 15 },
  { codigo_ciudad: 15189, nombre_ciudad: "CIENEGA", codigo_departamento: 15 },
  { codigo_ciudad: 15204, nombre_ciudad: "COMBITA", codigo_departamento: 15 },
  { codigo_ciudad: 15212, nombre_ciudad: "COPER", codigo_departamento: 15 },
  { codigo_ciudad: 15215, nombre_ciudad: "CORRALES", codigo_departamento: 15 },
  {
    codigo_ciudad: 15218,
    nombre_ciudad: "COVARACHIA",
    codigo_departamento: 15,
  },
  { codigo_ciudad: 15223, nombre_ciudad: "CUBARA", codigo_departamento: 15 },
  { codigo_ciudad: 19318, nombre_ciudad: "GUAPI", codigo_departamento: 19 },
  { codigo_ciudad: 15224, nombre_ciudad: "CUCAITA", codigo_departamento: 15 },
  { codigo_ciudad: 15226, nombre_ciudad: "CUITIVA", codigo_departamento: 15 },
  { codigo_ciudad: 15232, nombre_ciudad: "CHIQUIZA", codigo_departamento: 15 },
  { codigo_ciudad: 15236, nombre_ciudad: "CHIVOR", codigo_departamento: 15 },
  { codigo_ciudad: 15238, nombre_ciudad: "DUITAMA", codigo_departamento: 15 },
  { codigo_ciudad: 15244, nombre_ciudad: "EL COCUY", codigo_departamento: 15 },
  { codigo_ciudad: 15248, nombre_ciudad: "EL ESPINO", codigo_departamento: 15 },
  {
    codigo_ciudad: 15272,
    nombre_ciudad: "FIRAVITOBA",
    codigo_departamento: 15,
  },
  { codigo_ciudad: 15276, nombre_ciudad: "FLORESTA", codigo_departamento: 15 },
  {
    codigo_ciudad: 15293,
    nombre_ciudad: "GACHANTIVA",
    codigo_departamento: 15,
  },
  { codigo_ciudad: 15296, nombre_ciudad: "GAMEZA", codigo_departamento: 15 },
  { codigo_ciudad: 15299, nombre_ciudad: "GARAGOA", codigo_departamento: 15 },
  {
    codigo_ciudad: 15317,
    nombre_ciudad: "GUACAMAYAS",
    codigo_departamento: 15,
  },
  { codigo_ciudad: 15322, nombre_ciudad: "GUATEQUE", codigo_departamento: 15 },
  { codigo_ciudad: 15325, nombre_ciudad: "GUAYATA", codigo_departamento: 15 },
  {
    codigo_ciudad: 15332,
    nombre_ciudad: "GÜICAN DE LA SIERRA",
    codigo_departamento: 15,
  },
  { codigo_ciudad: 15362, nombre_ciudad: "IZA", codigo_departamento: 15 },
  { codigo_ciudad: 15367, nombre_ciudad: "JENESANO", codigo_departamento: 15 },
  { codigo_ciudad: 15368, nombre_ciudad: "JERICO", codigo_departamento: 15 },
  {
    codigo_ciudad: 15377,
    nombre_ciudad: "LABRANZAGRANDE",
    codigo_departamento: 15,
  },
  {
    codigo_ciudad: 15380,
    nombre_ciudad: "LA CAPILLA",
    codigo_departamento: 15,
  },
  {
    codigo_ciudad: 15401,
    nombre_ciudad: "LA VICTORIA",
    codigo_departamento: 15,
  },
  { codigo_ciudad: 15403, nombre_ciudad: "LA UVITA", codigo_departamento: 15 },
  {
    codigo_ciudad: 15407,
    nombre_ciudad: "VILLA DE LEYVA",
    codigo_departamento: 15,
  },
  { codigo_ciudad: 15425, nombre_ciudad: "MACANAL", codigo_departamento: 15 },
  { codigo_ciudad: 15442, nombre_ciudad: "MARIPI", codigo_departamento: 15 },
  {
    codigo_ciudad: 15455,
    nombre_ciudad: "MIRAFLORES",
    codigo_departamento: 15,
  },
  { codigo_ciudad: 15464, nombre_ciudad: "MONGUA", codigo_departamento: 15 },
  { codigo_ciudad: 15466, nombre_ciudad: "MONGUI", codigo_departamento: 15 },
  { codigo_ciudad: 15469, nombre_ciudad: "MONIQUIRA", codigo_departamento: 15 },
  { codigo_ciudad: 15476, nombre_ciudad: "MOTAVITA", codigo_departamento: 15 },
  { codigo_ciudad: 15480, nombre_ciudad: "MUZO", codigo_departamento: 15 },
  { codigo_ciudad: 15491, nombre_ciudad: "NOBSA", codigo_departamento: 15 },
  {
    codigo_ciudad: 15494,
    nombre_ciudad: "NUEVO COLON",
    codigo_departamento: 15,
  },
  { codigo_ciudad: 15500, nombre_ciudad: "OICATA", codigo_departamento: 15 },
  { codigo_ciudad: 15507, nombre_ciudad: "OTANCHE", codigo_departamento: 15 },
  { codigo_ciudad: 15511, nombre_ciudad: "PACHAVITA", codigo_departamento: 15 },
  { codigo_ciudad: 15514, nombre_ciudad: "PAEZ", codigo_departamento: 15 },
  { codigo_ciudad: 15516, nombre_ciudad: "PAIPA", codigo_departamento: 15 },
  { codigo_ciudad: 15518, nombre_ciudad: "PAJARITO", codigo_departamento: 15 },
  { codigo_ciudad: 15522, nombre_ciudad: "PANQUEBA", codigo_departamento: 15 },
  { codigo_ciudad: 15531, nombre_ciudad: "PAUNA", codigo_departamento: 15 },
  { codigo_ciudad: 15533, nombre_ciudad: "PAYA", codigo_departamento: 15 },
  {
    codigo_ciudad: 15537,
    nombre_ciudad: "PAZ DE RIO",
    codigo_departamento: 15,
  },
  { codigo_ciudad: 15542, nombre_ciudad: "PESCA", codigo_departamento: 15 },
  { codigo_ciudad: 15550, nombre_ciudad: "PISBA", codigo_departamento: 15 },
  {
    codigo_ciudad: 15572,
    nombre_ciudad: "PUERTO BOYACA",
    codigo_departamento: 15,
  },
  { codigo_ciudad: 15580, nombre_ciudad: "QUIPAMA", codigo_departamento: 15 },
  { codigo_ciudad: 15599, nombre_ciudad: "RAMIRIQUI", codigo_departamento: 15 },
  { codigo_ciudad: 15600, nombre_ciudad: "RAQUIRA", codigo_departamento: 15 },
  { codigo_ciudad: 15621, nombre_ciudad: "RONDON", codigo_departamento: 15 },
  { codigo_ciudad: 15632, nombre_ciudad: "SABOYA", codigo_departamento: 15 },
  { codigo_ciudad: 15638, nombre_ciudad: "SACHICA", codigo_departamento: 15 },
  { codigo_ciudad: 15646, nombre_ciudad: "SAMACA", codigo_departamento: 15 },
  {
    codigo_ciudad: 15660,
    nombre_ciudad: "SAN EDUARDO",
    codigo_departamento: 15,
  },
  {
    codigo_ciudad: 15664,
    nombre_ciudad: "SAN JOSE DE PARE",
    codigo_departamento: 15,
  },
  {
    codigo_ciudad: 15667,
    nombre_ciudad: "SAN LUIS DE GACENO",
    codigo_departamento: 15,
  },
  { codigo_ciudad: 15673, nombre_ciudad: "SAN MATEO", codigo_departamento: 15 },
  {
    codigo_ciudad: 15676,
    nombre_ciudad: "SAN MIGUEL DE SEMA",
    codigo_departamento: 15,
  },
  {
    codigo_ciudad: 15681,
    nombre_ciudad: "SAN PABLO DE BORBUR",
    codigo_departamento: 15,
  },
  { codigo_ciudad: 15686, nombre_ciudad: "SANTANA", codigo_departamento: 15 },
  {
    codigo_ciudad: 15690,
    nombre_ciudad: "SANTA MARIA",
    codigo_departamento: 15,
  },
  {
    codigo_ciudad: 15693,
    nombre_ciudad: "SANTA ROSA DE VITERBO",
    codigo_departamento: 15,
  },
  {
    codigo_ciudad: 15696,
    nombre_ciudad: "SANTA SOFIA",
    codigo_departamento: 15,
  },
  {
    codigo_ciudad: 15720,
    nombre_ciudad: "SATIVANORTE",
    codigo_departamento: 15,
  },
  { codigo_ciudad: 15723, nombre_ciudad: "SATIVASUR", codigo_departamento: 15 },
  { codigo_ciudad: 15740, nombre_ciudad: "SIACHOQUE", codigo_departamento: 15 },
  { codigo_ciudad: 15753, nombre_ciudad: "SOATA", codigo_departamento: 15 },
  { codigo_ciudad: 15755, nombre_ciudad: "SOCOTA", codigo_departamento: 15 },
  { codigo_ciudad: 15757, nombre_ciudad: "SOCHA", codigo_departamento: 15 },
  { codigo_ciudad: 15759, nombre_ciudad: "SOGAMOSO", codigo_departamento: 15 },
  { codigo_ciudad: 15761, nombre_ciudad: "SOMONDOCO", codigo_departamento: 15 },
  { codigo_ciudad: 15762, nombre_ciudad: "SORA", codigo_departamento: 15 },
  { codigo_ciudad: 15763, nombre_ciudad: "SOTAQUIRA", codigo_departamento: 15 },
  { codigo_ciudad: 15764, nombre_ciudad: "SORACA", codigo_departamento: 15 },
  { codigo_ciudad: 15774, nombre_ciudad: "SUSACON", codigo_departamento: 15 },
  {
    codigo_ciudad: 15776,
    nombre_ciudad: "SUTAMARCHAN",
    codigo_departamento: 15,
  },
  { codigo_ciudad: 15778, nombre_ciudad: "SUTATENZA", codigo_departamento: 15 },
  { codigo_ciudad: 15790, nombre_ciudad: "TASCO", codigo_departamento: 15 },
  { codigo_ciudad: 15798, nombre_ciudad: "TENZA", codigo_departamento: 15 },
  { codigo_ciudad: 15804, nombre_ciudad: "TIBANA", codigo_departamento: 15 },
  { codigo_ciudad: 15806, nombre_ciudad: "TIBASOSA", codigo_departamento: 15 },
  { codigo_ciudad: 15808, nombre_ciudad: "TINJACA", codigo_departamento: 15 },
  { codigo_ciudad: 15810, nombre_ciudad: "TIPACOQUE", codigo_departamento: 15 },
  { codigo_ciudad: 15814, nombre_ciudad: "TOCA", codigo_departamento: 15 },
  { codigo_ciudad: 15816, nombre_ciudad: "TOGÜI", codigo_departamento: 15 },
  { codigo_ciudad: 15820, nombre_ciudad: "TOPAGA", codigo_departamento: 15 },
  { codigo_ciudad: 15822, nombre_ciudad: "TOTA", codigo_departamento: 15 },
  { codigo_ciudad: 15832, nombre_ciudad: "TUNUNGUA", codigo_departamento: 15 },
  { codigo_ciudad: 15835, nombre_ciudad: "TURMEQUE", codigo_departamento: 15 },
  { codigo_ciudad: 15837, nombre_ciudad: "TUTA", codigo_departamento: 15 },
  { codigo_ciudad: 15839, nombre_ciudad: "TUTAZA", codigo_departamento: 15 },
  { codigo_ciudad: 15842, nombre_ciudad: "UMBITA", codigo_departamento: 15 },
  {
    codigo_ciudad: 15861,
    nombre_ciudad: "VENTAQUEMADA",
    codigo_departamento: 15,
  },
  { codigo_ciudad: 15879, nombre_ciudad: "VIRACACHA", codigo_departamento: 15 },
  { codigo_ciudad: 15897, nombre_ciudad: "ZETAQUIRA", codigo_departamento: 15 },
  { codigo_ciudad: 17001, nombre_ciudad: "MANIZALES", codigo_departamento: 17 },
  { codigo_ciudad: 17013, nombre_ciudad: "AGUADAS", codigo_departamento: 17 },
  { codigo_ciudad: 17042, nombre_ciudad: "ANSERMA", codigo_departamento: 17 },
  { codigo_ciudad: 17050, nombre_ciudad: "ARANZAZU", codigo_departamento: 17 },
  {
    codigo_ciudad: 17088,
    nombre_ciudad: "BELALCAZAR",
    codigo_departamento: 17,
  },
  { codigo_ciudad: 17174, nombre_ciudad: "CHINCHINA", codigo_departamento: 17 },
  {
    codigo_ciudad: 17272,
    nombre_ciudad: "FILADELFIA",
    codigo_departamento: 17,
  },
  { codigo_ciudad: 17380, nombre_ciudad: "LA DORADA", codigo_departamento: 17 },
  { codigo_ciudad: 17388, nombre_ciudad: "LA MERCED", codigo_departamento: 17 },
  {
    codigo_ciudad: 17433,
    nombre_ciudad: "MANZANARES",
    codigo_departamento: 17,
  },
  { codigo_ciudad: 17442, nombre_ciudad: "MARMATO", codigo_departamento: 17 },
  {
    codigo_ciudad: 17444,
    nombre_ciudad: "MARQUETALIA",
    codigo_departamento: 17,
  },
  { codigo_ciudad: 17446, nombre_ciudad: "MARULANDA", codigo_departamento: 17 },
  { codigo_ciudad: 17486, nombre_ciudad: "NEIRA", codigo_departamento: 17 },
  { codigo_ciudad: 17495, nombre_ciudad: "NORCASIA", codigo_departamento: 17 },
  { codigo_ciudad: 17513, nombre_ciudad: "PACORA", codigo_departamento: 17 },
  { codigo_ciudad: 17524, nombre_ciudad: "PALESTINA", codigo_departamento: 17 },
  {
    codigo_ciudad: 17541,
    nombre_ciudad: "PENSILVANIA",
    codigo_departamento: 17,
  },
  { codigo_ciudad: 17614, nombre_ciudad: "RIOSUCIO", codigo_departamento: 17 },
  { codigo_ciudad: 17616, nombre_ciudad: "RISARALDA", codigo_departamento: 17 },
  { codigo_ciudad: 17653, nombre_ciudad: "SALAMINA", codigo_departamento: 17 },
  { codigo_ciudad: 17662, nombre_ciudad: "SAMANA", codigo_departamento: 17 },
  { codigo_ciudad: 17665, nombre_ciudad: "SAN JOSE", codigo_departamento: 17 },
  { codigo_ciudad: 17777, nombre_ciudad: "SUPIA", codigo_departamento: 17 },
  { codigo_ciudad: 17867, nombre_ciudad: "VICTORIA", codigo_departamento: 17 },
  {
    codigo_ciudad: 17873,
    nombre_ciudad: "VILLAMARIA",
    codigo_departamento: 17,
  },
  { codigo_ciudad: 17877, nombre_ciudad: "VITERBO", codigo_departamento: 17 },
  { codigo_ciudad: 18001, nombre_ciudad: "FLORENCIA", codigo_departamento: 18 },
  { codigo_ciudad: 18029, nombre_ciudad: "ALBANIA", codigo_departamento: 18 },
  {
    codigo_ciudad: 18094,
    nombre_ciudad: "BELEN DE LOS ANDAQUIES",
    codigo_departamento: 18,
  },
  {
    codigo_ciudad: 18150,
    nombre_ciudad: "CARTAGENA DEL CHAIRA",
    codigo_departamento: 18,
  },
  { codigo_ciudad: 18205, nombre_ciudad: "CURILLO", codigo_departamento: 18 },
  {
    codigo_ciudad: 18247,
    nombre_ciudad: "EL DONCELLO",
    codigo_departamento: 18,
  },
  { codigo_ciudad: 18256, nombre_ciudad: "EL PAUJIL", codigo_departamento: 18 },
  {
    codigo_ciudad: 18410,
    nombre_ciudad: "LA MONTAÑITA",
    codigo_departamento: 18,
  },
  { codigo_ciudad: 18460, nombre_ciudad: "MILAN", codigo_departamento: 18 },
  { codigo_ciudad: 18479, nombre_ciudad: "MORELIA", codigo_departamento: 18 },
  {
    codigo_ciudad: 18592,
    nombre_ciudad: "PUERTO RICO",
    codigo_departamento: 18,
  },
  {
    codigo_ciudad: 18610,
    nombre_ciudad: "SAN JOSE DEL FRAGUA",
    codigo_departamento: 18,
  },
  {
    codigo_ciudad: 18753,
    nombre_ciudad: "SAN VICENTE DEL CAGUAN",
    codigo_departamento: 18,
  },
  { codigo_ciudad: 18756, nombre_ciudad: "SOLANO", codigo_departamento: 18 },
  { codigo_ciudad: 18785, nombre_ciudad: "SOLITA", codigo_departamento: 18 },
  {
    codigo_ciudad: 18860,
    nombre_ciudad: "VALPARAISO",
    codigo_departamento: 18,
  },
  { codigo_ciudad: 19001, nombre_ciudad: "POPAYAN", codigo_departamento: 19 },
  { codigo_ciudad: 19022, nombre_ciudad: "ALMAGUER", codigo_departamento: 19 },
  { codigo_ciudad: 19050, nombre_ciudad: "ARGELIA", codigo_departamento: 19 },
  { codigo_ciudad: 19075, nombre_ciudad: "BALBOA", codigo_departamento: 19 },
  { codigo_ciudad: 19100, nombre_ciudad: "BOLIVAR", codigo_departamento: 19 },
  {
    codigo_ciudad: 19110,
    nombre_ciudad: "BUENOS AIRES",
    codigo_departamento: 19,
  },
  { codigo_ciudad: 19130, nombre_ciudad: "CAJIBIO", codigo_departamento: 19 },
  { codigo_ciudad: 19137, nombre_ciudad: "CALDONO", codigo_departamento: 19 },
  { codigo_ciudad: 19142, nombre_ciudad: "CALOTO", codigo_departamento: 19 },
  { codigo_ciudad: 19212, nombre_ciudad: "CORINTO", codigo_departamento: 19 },
  { codigo_ciudad: 19256, nombre_ciudad: "EL TAMBO", codigo_departamento: 19 },
  { codigo_ciudad: 19290, nombre_ciudad: "FLORENCIA", codigo_departamento: 19 },
  { codigo_ciudad: 19300, nombre_ciudad: "GUACHENE", codigo_departamento: 19 },
  { codigo_ciudad: 19355, nombre_ciudad: "INZA", codigo_departamento: 19 },
  { codigo_ciudad: 19364, nombre_ciudad: "JAMBALO", codigo_departamento: 19 },
  { codigo_ciudad: 19392, nombre_ciudad: "LA SIERRA", codigo_departamento: 19 },
  { codigo_ciudad: 19397, nombre_ciudad: "LA VEGA", codigo_departamento: 19 },
  {
    codigo_ciudad: 19418,
    nombre_ciudad: "LOPEZ DE MICAY",
    codigo_departamento: 19,
  },
  {
    codigo_ciudad: 19450,
    nombre_ciudad: "MERCADERES",
    codigo_departamento: 19,
  },
  { codigo_ciudad: 19455, nombre_ciudad: "MIRANDA", codigo_departamento: 19 },
  { codigo_ciudad: 19473, nombre_ciudad: "MORALES", codigo_departamento: 19 },
  { codigo_ciudad: 19513, nombre_ciudad: "PADILLA", codigo_departamento: 19 },
  { codigo_ciudad: 19517, nombre_ciudad: "PAEZ", codigo_departamento: 19 },
  { codigo_ciudad: 19532, nombre_ciudad: "PATIA", codigo_departamento: 19 },
  { codigo_ciudad: 19533, nombre_ciudad: "PIAMONTE", codigo_departamento: 19 },
  {
    codigo_ciudad: 19548,
    nombre_ciudad: "PIENDAMO - TUNIA",
    codigo_departamento: 19,
  },
  {
    codigo_ciudad: 19573,
    nombre_ciudad: "PUERTO TEJADA",
    codigo_departamento: 19,
  },
  { codigo_ciudad: 19585, nombre_ciudad: "PURACE", codigo_departamento: 19 },
  { codigo_ciudad: 19622, nombre_ciudad: "ROSAS", codigo_departamento: 19 },
  {
    codigo_ciudad: 19693,
    nombre_ciudad: "SAN SEBASTIAN",
    codigo_departamento: 19,
  },
  {
    codigo_ciudad: 19698,
    nombre_ciudad: "SANTANDER DE QUILICHAO",
    codigo_departamento: 19,
  },
  {
    codigo_ciudad: 19701,
    nombre_ciudad: "SANTA ROSA",
    codigo_departamento: 19,
  },
  { codigo_ciudad: 19743, nombre_ciudad: "SILVIA", codigo_departamento: 19 },
  {
    codigo_ciudad: 19760,
    nombre_ciudad: "SOTARA PAISPAMBA",
    codigo_departamento: 19,
  },
  { codigo_ciudad: 19780, nombre_ciudad: "SUAREZ", codigo_departamento: 19 },
  { codigo_ciudad: 19785, nombre_ciudad: "SUCRE", codigo_departamento: 19 },
  { codigo_ciudad: 19807, nombre_ciudad: "TIMBIO", codigo_departamento: 19 },
  { codigo_ciudad: 19809, nombre_ciudad: "TIMBIQUI", codigo_departamento: 19 },
  { codigo_ciudad: 19821, nombre_ciudad: "TORIBIO", codigo_departamento: 19 },
  { codigo_ciudad: 19824, nombre_ciudad: "TOTORO", codigo_departamento: 19 },
  {
    codigo_ciudad: 19845,
    nombre_ciudad: "VILLA RICA",
    codigo_departamento: 19,
  },
  {
    codigo_ciudad: 20001,
    nombre_ciudad: "VALLEDUPAR",
    codigo_departamento: 20,
  },
  { codigo_ciudad: 20011, nombre_ciudad: "AGUACHICA", codigo_departamento: 20 },
  {
    codigo_ciudad: 20013,
    nombre_ciudad: "AGUSTIN CODAZZI",
    codigo_departamento: 20,
  },
  { codigo_ciudad: 20032, nombre_ciudad: "ASTREA", codigo_departamento: 20 },
  { codigo_ciudad: 20045, nombre_ciudad: "BECERRIL", codigo_departamento: 20 },
  { codigo_ciudad: 20060, nombre_ciudad: "BOSCONIA", codigo_departamento: 20 },
  {
    codigo_ciudad: 20175,
    nombre_ciudad: "CHIMICHAGUA",
    codigo_departamento: 20,
  },
  {
    codigo_ciudad: 20178,
    nombre_ciudad: "CHIRIGUANA",
    codigo_departamento: 20,
  },
  { codigo_ciudad: 20228, nombre_ciudad: "CURUMANI", codigo_departamento: 20 },
  { codigo_ciudad: 20238, nombre_ciudad: "EL COPEY", codigo_departamento: 20 },
  { codigo_ciudad: 20250, nombre_ciudad: "EL PASO", codigo_departamento: 20 },
  { codigo_ciudad: 20295, nombre_ciudad: "GAMARRA", codigo_departamento: 20 },
  { codigo_ciudad: 20310, nombre_ciudad: "GONZALEZ", codigo_departamento: 20 },
  { codigo_ciudad: 20383, nombre_ciudad: "LA GLORIA", codigo_departamento: 20 },
  {
    codigo_ciudad: 20400,
    nombre_ciudad: "LA JAGUA DE IBIRICO",
    codigo_departamento: 20,
  },
  {
    codigo_ciudad: 20443,
    nombre_ciudad: "MANAURE BALCON DEL CESAR",
    codigo_departamento: 20,
  },
  { codigo_ciudad: 20517, nombre_ciudad: "PAILITAS", codigo_departamento: 20 },
  { codigo_ciudad: 20550, nombre_ciudad: "PELAYA", codigo_departamento: 20 },
  {
    codigo_ciudad: 20570,
    nombre_ciudad: "PUEBLO BELLO",
    codigo_departamento: 20,
  },
  {
    codigo_ciudad: 20614,
    nombre_ciudad: "RIO DE ORO",
    codigo_departamento: 20,
  },
  { codigo_ciudad: 20621, nombre_ciudad: "LA PAZ", codigo_departamento: 20 },
  {
    codigo_ciudad: 20710,
    nombre_ciudad: "SAN ALBERTO",
    codigo_departamento: 20,
  },
  { codigo_ciudad: 20750, nombre_ciudad: "SAN DIEGO", codigo_departamento: 20 },
  {
    codigo_ciudad: 20770,
    nombre_ciudad: "SAN MARTIN",
    codigo_departamento: 20,
  },
  {
    codigo_ciudad: 20787,
    nombre_ciudad: "TAMALAMEQUE",
    codigo_departamento: 20,
  },
  { codigo_ciudad: 23001, nombre_ciudad: "MONTERIA", codigo_departamento: 23 },
  { codigo_ciudad: 23068, nombre_ciudad: "AYAPEL", codigo_departamento: 23 },
  {
    codigo_ciudad: 23079,
    nombre_ciudad: "BUENAVISTA",
    codigo_departamento: 23,
  },
  { codigo_ciudad: 23090, nombre_ciudad: "CANALETE", codigo_departamento: 23 },
  { codigo_ciudad: 23162, nombre_ciudad: "CERETE", codigo_departamento: 23 },
  { codigo_ciudad: 23168, nombre_ciudad: "CHIMA", codigo_departamento: 23 },
  { codigo_ciudad: 23182, nombre_ciudad: "CHINU", codigo_departamento: 23 },
  {
    codigo_ciudad: 23189,
    nombre_ciudad: "CIENAGA DE ORO",
    codigo_departamento: 23,
  },
  { codigo_ciudad: 23300, nombre_ciudad: "COTORRA", codigo_departamento: 23 },
  {
    codigo_ciudad: 23350,
    nombre_ciudad: "LA APARTADA",
    codigo_departamento: 23,
  },
  { codigo_ciudad: 23417, nombre_ciudad: "LORICA", codigo_departamento: 23 },
  {
    codigo_ciudad: 23419,
    nombre_ciudad: "LOS CORDOBAS",
    codigo_departamento: 23,
  },
  { codigo_ciudad: 23464, nombre_ciudad: "MOMIL", codigo_departamento: 23 },
  {
    codigo_ciudad: 23466,
    nombre_ciudad: "MONTELIBANO",
    codigo_departamento: 23,
  },
  { codigo_ciudad: 23500, nombre_ciudad: "MOÑITOS", codigo_departamento: 23 },
  {
    codigo_ciudad: 23555,
    nombre_ciudad: "PLANETA RICA",
    codigo_departamento: 23,
  },
  {
    codigo_ciudad: 23570,
    nombre_ciudad: "PUEBLO NUEVO",
    codigo_departamento: 23,
  },
  {
    codigo_ciudad: 23574,
    nombre_ciudad: "PUERTO ESCONDIDO",
    codigo_departamento: 23,
  },
  {
    codigo_ciudad: 23580,
    nombre_ciudad: "PUERTO LIBERTADOR",
    codigo_departamento: 23,
  },
  {
    codigo_ciudad: 23586,
    nombre_ciudad: "PURISIMA DE LA CONCEPCION",
    codigo_departamento: 23,
  },
  { codigo_ciudad: 23660, nombre_ciudad: "SAHAGUN", codigo_departamento: 23 },
  {
    codigo_ciudad: 23670,
    nombre_ciudad: "SAN ANDRES DE SOTAVENTO",
    codigo_departamento: 23,
  },
  {
    codigo_ciudad: 23672,
    nombre_ciudad: "SAN ANTERO",
    codigo_departamento: 23,
  },
  {
    codigo_ciudad: 23675,
    nombre_ciudad: "SAN BERNARDO DEL VIENTO",
    codigo_departamento: 23,
  },
  {
    codigo_ciudad: 23678,
    nombre_ciudad: "SAN CARLOS",
    codigo_departamento: 23,
  },
  {
    codigo_ciudad: 23682,
    nombre_ciudad: "SAN JOSE DE URE",
    codigo_departamento: 23,
  },
  {
    codigo_ciudad: 23686,
    nombre_ciudad: "SAN PELAYO",
    codigo_departamento: 23,
  },
  { codigo_ciudad: 23807, nombre_ciudad: "TIERRALTA", codigo_departamento: 23 },
  { codigo_ciudad: 23815, nombre_ciudad: "TUCHIN", codigo_departamento: 23 },
  { codigo_ciudad: 23855, nombre_ciudad: "VALENCIA", codigo_departamento: 23 },
  {
    codigo_ciudad: 25001,
    nombre_ciudad: "AGUA DE DIOS",
    codigo_departamento: 25,
  },
  { codigo_ciudad: 25019, nombre_ciudad: "ALBAN", codigo_departamento: 25 },
  { codigo_ciudad: 25035, nombre_ciudad: "ANAPOIMA", codigo_departamento: 25 },
  { codigo_ciudad: 25040, nombre_ciudad: "ANOLAIMA", codigo_departamento: 25 },
  { codigo_ciudad: 25053, nombre_ciudad: "ARBELAEZ", codigo_departamento: 25 },
  { codigo_ciudad: 25086, nombre_ciudad: "BELTRAN", codigo_departamento: 25 },
  { codigo_ciudad: 25095, nombre_ciudad: "BITUIMA", codigo_departamento: 25 },
  { codigo_ciudad: 25099, nombre_ciudad: "BOJACA", codigo_departamento: 25 },
  { codigo_ciudad: 25120, nombre_ciudad: "CABRERA", codigo_departamento: 25 },
  { codigo_ciudad: 25123, nombre_ciudad: "CACHIPAY", codigo_departamento: 25 },
  { codigo_ciudad: 25126, nombre_ciudad: "CAJICA", codigo_departamento: 25 },
  { codigo_ciudad: 25148, nombre_ciudad: "CAPARRAPI", codigo_departamento: 25 },
  { codigo_ciudad: 25151, nombre_ciudad: "CAQUEZA", codigo_departamento: 25 },
  {
    codigo_ciudad: 25154,
    nombre_ciudad: "CARMEN DE CARUPA",
    codigo_departamento: 25,
  },
  { codigo_ciudad: 25168, nombre_ciudad: "CHAGUANI", codigo_departamento: 25 },
  { codigo_ciudad: 25175, nombre_ciudad: "CHIA", codigo_departamento: 25 },
  { codigo_ciudad: 25178, nombre_ciudad: "CHIPAQUE", codigo_departamento: 25 },
  { codigo_ciudad: 25181, nombre_ciudad: "CHOACHI", codigo_departamento: 25 },
  { codigo_ciudad: 25183, nombre_ciudad: "CHOCONTA", codigo_departamento: 25 },
  { codigo_ciudad: 25200, nombre_ciudad: "COGUA", codigo_departamento: 25 },
  { codigo_ciudad: 25214, nombre_ciudad: "COTA", codigo_departamento: 25 },
  { codigo_ciudad: 25224, nombre_ciudad: "CUCUNUBA", codigo_departamento: 25 },
  {
    codigo_ciudad: 25245,
    nombre_ciudad: "EL COLEGIO",
    codigo_departamento: 25,
  },
  { codigo_ciudad: 25258, nombre_ciudad: "EL PEÑON", codigo_departamento: 25 },
  { codigo_ciudad: 25260, nombre_ciudad: "EL ROSAL", codigo_departamento: 25 },
  {
    codigo_ciudad: 25269,
    nombre_ciudad: "FACATATIVA",
    codigo_departamento: 25,
  },
  { codigo_ciudad: 25279, nombre_ciudad: "FOMEQUE", codigo_departamento: 25 },
  { codigo_ciudad: 25281, nombre_ciudad: "FOSCA", codigo_departamento: 25 },
  { codigo_ciudad: 25286, nombre_ciudad: "FUNZA", codigo_departamento: 25 },
  { codigo_ciudad: 25288, nombre_ciudad: "FUQUENE", codigo_departamento: 25 },
  {
    codigo_ciudad: 25290,
    nombre_ciudad: "FUSAGASUGA",
    codigo_departamento: 25,
  },
  { codigo_ciudad: 25293, nombre_ciudad: "GACHALA", codigo_departamento: 25 },
  {
    codigo_ciudad: 25295,
    nombre_ciudad: "GACHANCIPA",
    codigo_departamento: 25,
  },
  { codigo_ciudad: 25297, nombre_ciudad: "GACHETA", codigo_departamento: 25 },
  { codigo_ciudad: 25299, nombre_ciudad: "GAMA", codigo_departamento: 25 },
  { codigo_ciudad: 25307, nombre_ciudad: "GIRARDOT", codigo_departamento: 25 },
  { codigo_ciudad: 25312, nombre_ciudad: "GRANADA", codigo_departamento: 25 },
  { codigo_ciudad: 25317, nombre_ciudad: "GUACHETA", codigo_departamento: 25 },
  { codigo_ciudad: 25320, nombre_ciudad: "GUADUAS", codigo_departamento: 25 },
  { codigo_ciudad: 25322, nombre_ciudad: "GUASCA", codigo_departamento: 25 },
  { codigo_ciudad: 25324, nombre_ciudad: "GUATAQUI", codigo_departamento: 25 },
  { codigo_ciudad: 25326, nombre_ciudad: "GUATAVITA", codigo_departamento: 25 },
  {
    codigo_ciudad: 25328,
    nombre_ciudad: "GUAYABAL DE SIQUIMA",
    codigo_departamento: 25,
  },
  {
    codigo_ciudad: 25335,
    nombre_ciudad: "GUAYABETAL",
    codigo_departamento: 25,
  },
  { codigo_ciudad: 25339, nombre_ciudad: "GUTIERREZ", codigo_departamento: 25 },
  { codigo_ciudad: 25368, nombre_ciudad: "JERUSALEN", codigo_departamento: 25 },
  { codigo_ciudad: 25372, nombre_ciudad: "JUNIN", codigo_departamento: 25 },
  { codigo_ciudad: 25377, nombre_ciudad: "LA CALERA", codigo_departamento: 25 },
  { codigo_ciudad: 25386, nombre_ciudad: "LA MESA", codigo_departamento: 25 },
  { codigo_ciudad: 25394, nombre_ciudad: "LA PALMA", codigo_departamento: 25 },
  { codigo_ciudad: 25398, nombre_ciudad: "LA PEÑA", codigo_departamento: 25 },
  { codigo_ciudad: 25402, nombre_ciudad: "LA VEGA", codigo_departamento: 25 },
  {
    codigo_ciudad: 25407,
    nombre_ciudad: "LENGUAZAQUE",
    codigo_departamento: 25,
  },
  { codigo_ciudad: 25426, nombre_ciudad: "MACHETA", codigo_departamento: 25 },
  { codigo_ciudad: 25430, nombre_ciudad: "MADRID", codigo_departamento: 25 },
  { codigo_ciudad: 25436, nombre_ciudad: "MANTA", codigo_departamento: 25 },
  { codigo_ciudad: 25438, nombre_ciudad: "MEDINA", codigo_departamento: 25 },
  { codigo_ciudad: 25473, nombre_ciudad: "MOSQUERA", codigo_departamento: 25 },
  { codigo_ciudad: 25483, nombre_ciudad: "NARIÑO", codigo_departamento: 25 },
  { codigo_ciudad: 25486, nombre_ciudad: "NEMOCON", codigo_departamento: 25 },
  { codigo_ciudad: 25488, nombre_ciudad: "NILO", codigo_departamento: 25 },
  { codigo_ciudad: 25489, nombre_ciudad: "NIMAIMA", codigo_departamento: 25 },
  { codigo_ciudad: 25491, nombre_ciudad: "NOCAIMA", codigo_departamento: 25 },
  { codigo_ciudad: 25506, nombre_ciudad: "VENECIA", codigo_departamento: 25 },
  { codigo_ciudad: 25513, nombre_ciudad: "PACHO", codigo_departamento: 25 },
  { codigo_ciudad: 25518, nombre_ciudad: "PAIME", codigo_departamento: 25 },
  { codigo_ciudad: 25524, nombre_ciudad: "PANDI", codigo_departamento: 25 },
  {
    codigo_ciudad: 25530,
    nombre_ciudad: "PARATEBUENO",
    codigo_departamento: 25,
  },
  { codigo_ciudad: 25535, nombre_ciudad: "PASCA", codigo_departamento: 25 },
  {
    codigo_ciudad: 25572,
    nombre_ciudad: "PUERTO SALGAR",
    codigo_departamento: 25,
  },
  { codigo_ciudad: 25580, nombre_ciudad: "PULI", codigo_departamento: 25 },
  {
    codigo_ciudad: 25592,
    nombre_ciudad: "QUEBRADANEGRA",
    codigo_departamento: 25,
  },
  { codigo_ciudad: 25594, nombre_ciudad: "QUETAME", codigo_departamento: 25 },
  { codigo_ciudad: 25596, nombre_ciudad: "QUIPILE", codigo_departamento: 25 },
  { codigo_ciudad: 25599, nombre_ciudad: "APULO", codigo_departamento: 25 },
  { codigo_ciudad: 25612, nombre_ciudad: "RICAURTE", codigo_departamento: 25 },
  {
    codigo_ciudad: 25645,
    nombre_ciudad: "SAN ANTONIO DEL TEQUENDAMA",
    codigo_departamento: 25,
  },
  {
    codigo_ciudad: 25649,
    nombre_ciudad: "SAN BERNARDO",
    codigo_departamento: 25,
  },
  {
    codigo_ciudad: 25653,
    nombre_ciudad: "SAN CAYETANO",
    codigo_departamento: 25,
  },
  {
    codigo_ciudad: 25658,
    nombre_ciudad: "SAN FRANCISCO",
    codigo_departamento: 25,
  },
  {
    codigo_ciudad: 25662,
    nombre_ciudad: "SAN JUAN DE RIOSECO",
    codigo_departamento: 25,
  },
  { codigo_ciudad: 25718, nombre_ciudad: "SASAIMA", codigo_departamento: 25 },
  { codigo_ciudad: 25736, nombre_ciudad: "SESQUILE", codigo_departamento: 25 },
  { codigo_ciudad: 25740, nombre_ciudad: "SIBATE", codigo_departamento: 25 },
  { codigo_ciudad: 25743, nombre_ciudad: "SILVANIA", codigo_departamento: 25 },
  { codigo_ciudad: 25745, nombre_ciudad: "SIMIJACA", codigo_departamento: 25 },
  { codigo_ciudad: 25754, nombre_ciudad: "SOACHA", codigo_departamento: 25 },
  { codigo_ciudad: 25758, nombre_ciudad: "SOPO", codigo_departamento: 25 },
  {
    codigo_ciudad: 25769,
    nombre_ciudad: "SUBACHOQUE",
    codigo_departamento: 25,
  },
  { codigo_ciudad: 25772, nombre_ciudad: "SUESCA", codigo_departamento: 25 },
  { codigo_ciudad: 25777, nombre_ciudad: "SUPATA", codigo_departamento: 25 },
  { codigo_ciudad: 25779, nombre_ciudad: "SUSA", codigo_departamento: 25 },
  { codigo_ciudad: 25781, nombre_ciudad: "SUTATAUSA", codigo_departamento: 25 },
  { codigo_ciudad: 25785, nombre_ciudad: "TABIO", codigo_departamento: 25 },
  { codigo_ciudad: 25793, nombre_ciudad: "TAUSA", codigo_departamento: 25 },
  { codigo_ciudad: 25797, nombre_ciudad: "TENA", codigo_departamento: 25 },
  { codigo_ciudad: 25799, nombre_ciudad: "TENJO", codigo_departamento: 25 },
  { codigo_ciudad: 25805, nombre_ciudad: "TIBACUY", codigo_departamento: 25 },
  { codigo_ciudad: 25807, nombre_ciudad: "TIBIRITA", codigo_departamento: 25 },
  { codigo_ciudad: 25815, nombre_ciudad: "TOCAIMA", codigo_departamento: 25 },
  { codigo_ciudad: 25817, nombre_ciudad: "TOCANCIPA", codigo_departamento: 25 },
  { codigo_ciudad: 25823, nombre_ciudad: "TOPAIPI", codigo_departamento: 25 },
  { codigo_ciudad: 25839, nombre_ciudad: "UBALA", codigo_departamento: 25 },
  { codigo_ciudad: 25841, nombre_ciudad: "UBAQUE", codigo_departamento: 25 },
  {
    codigo_ciudad: 25843,
    nombre_ciudad: "VILLA DE SAN DIEGO DE UBATE",
    codigo_departamento: 25,
  },
  { codigo_ciudad: 25845, nombre_ciudad: "UNE", codigo_departamento: 25 },
  { codigo_ciudad: 25851, nombre_ciudad: "UTICA", codigo_departamento: 25 },
  { codigo_ciudad: 25862, nombre_ciudad: "VERGARA", codigo_departamento: 25 },
  { codigo_ciudad: 25867, nombre_ciudad: "VIANI", codigo_departamento: 25 },
  {
    codigo_ciudad: 25871,
    nombre_ciudad: "VILLAGOMEZ",
    codigo_departamento: 25,
  },
  {
    codigo_ciudad: 25873,
    nombre_ciudad: "VILLAPINZON",
    codigo_departamento: 25,
  },
  { codigo_ciudad: 25875, nombre_ciudad: "VILLETA", codigo_departamento: 25 },
  { codigo_ciudad: 25878, nombre_ciudad: "VIOTA", codigo_departamento: 25 },
  { codigo_ciudad: 25885, nombre_ciudad: "YACOPI", codigo_departamento: 25 },
  { codigo_ciudad: 25898, nombre_ciudad: "ZIPACON", codigo_departamento: 25 },
  { codigo_ciudad: 25899, nombre_ciudad: "ZIPAQUIRA", codigo_departamento: 25 },
  { codigo_ciudad: 27001, nombre_ciudad: "QUIBDO", codigo_departamento: 27 },
  { codigo_ciudad: 27006, nombre_ciudad: "ACANDI", codigo_departamento: 27 },
  {
    codigo_ciudad: 27025,
    nombre_ciudad: "ALTO BAUDO",
    codigo_departamento: 27,
  },
  { codigo_ciudad: 27050, nombre_ciudad: "ATRATO", codigo_departamento: 27 },
  { codigo_ciudad: 27073, nombre_ciudad: "BAGADO", codigo_departamento: 27 },
  {
    codigo_ciudad: 27075,
    nombre_ciudad: "BAHIA SOLANO",
    codigo_departamento: 27,
  },
  {
    codigo_ciudad: 27077,
    nombre_ciudad: "BAJO BAUDO",
    codigo_departamento: 27,
  },
  { codigo_ciudad: 27099, nombre_ciudad: "BOJAYA", codigo_departamento: 27 },
  {
    codigo_ciudad: 27135,
    nombre_ciudad: "EL CANTON DEL SAN PABLO",
    codigo_departamento: 27,
  },
  {
    codigo_ciudad: 27150,
    nombre_ciudad: "CARMEN DEL DARIEN",
    codigo_departamento: 27,
  },
  { codigo_ciudad: 27160, nombre_ciudad: "CERTEGUI", codigo_departamento: 27 },
  { codigo_ciudad: 27205, nombre_ciudad: "CONDOTO", codigo_departamento: 27 },
  {
    codigo_ciudad: 27245,
    nombre_ciudad: "EL CARMEN DE ATRATO",
    codigo_departamento: 27,
  },
  {
    codigo_ciudad: 27250,
    nombre_ciudad: "EL LITORAL DEL SAN JUAN",
    codigo_departamento: 27,
  },
  { codigo_ciudad: 27361, nombre_ciudad: "ISTMINA", codigo_departamento: 27 },
  { codigo_ciudad: 27372, nombre_ciudad: "JURADO", codigo_departamento: 27 },
  { codigo_ciudad: 27413, nombre_ciudad: "LLORO", codigo_departamento: 27 },
  {
    codigo_ciudad: 27425,
    nombre_ciudad: "MEDIO ATRATO",
    codigo_departamento: 27,
  },
  {
    codigo_ciudad: 27430,
    nombre_ciudad: "MEDIO BAUDO",
    codigo_departamento: 27,
  },
  {
    codigo_ciudad: 27450,
    nombre_ciudad: "MEDIO SAN JUAN",
    codigo_departamento: 27,
  },
  { codigo_ciudad: 27491, nombre_ciudad: "NOVITA", codigo_departamento: 27 },
  { codigo_ciudad: 27495, nombre_ciudad: "NUQUI", codigo_departamento: 27 },
  { codigo_ciudad: 27580, nombre_ciudad: "RIO IRO", codigo_departamento: 27 },
  { codigo_ciudad: 27600, nombre_ciudad: "RIO QUITO", codigo_departamento: 27 },
  { codigo_ciudad: 27615, nombre_ciudad: "RIOSUCIO", codigo_departamento: 27 },
  {
    codigo_ciudad: 27660,
    nombre_ciudad: "SAN JOSE DEL PALMAR",
    codigo_departamento: 27,
  },
  { codigo_ciudad: 27745, nombre_ciudad: "SIPI", codigo_departamento: 27 },
  { codigo_ciudad: 27787, nombre_ciudad: "TADO", codigo_departamento: 27 },
  { codigo_ciudad: 27800, nombre_ciudad: "UNGUIA", codigo_departamento: 27 },
  {
    codigo_ciudad: 27810,
    nombre_ciudad: "UNION PANAMERICANA",
    codigo_departamento: 27,
  },
  { codigo_ciudad: 41001, nombre_ciudad: "NEIVA", codigo_departamento: 41 },
  { codigo_ciudad: 41006, nombre_ciudad: "ACEVEDO", codigo_departamento: 41 },
  { codigo_ciudad: 41013, nombre_ciudad: "AGRADO", codigo_departamento: 41 },
  { codigo_ciudad: 41016, nombre_ciudad: "AIPE", codigo_departamento: 41 },
  { codigo_ciudad: 41020, nombre_ciudad: "ALGECIRAS", codigo_departamento: 41 },
  { codigo_ciudad: 41026, nombre_ciudad: "ALTAMIRA", codigo_departamento: 41 },
  { codigo_ciudad: 41078, nombre_ciudad: "BARAYA", codigo_departamento: 41 },
  {
    codigo_ciudad: 41132,
    nombre_ciudad: "CAMPOALEGRE",
    codigo_departamento: 41,
  },
  { codigo_ciudad: 41206, nombre_ciudad: "COLOMBIA", codigo_departamento: 41 },
  { codigo_ciudad: 41244, nombre_ciudad: "ELIAS", codigo_departamento: 41 },
  { codigo_ciudad: 41298, nombre_ciudad: "GARZON", codigo_departamento: 41 },
  { codigo_ciudad: 41306, nombre_ciudad: "GIGANTE", codigo_departamento: 41 },
  { codigo_ciudad: 41319, nombre_ciudad: "GUADALUPE", codigo_departamento: 41 },
  { codigo_ciudad: 41349, nombre_ciudad: "HOBO", codigo_departamento: 41 },
  { codigo_ciudad: 41357, nombre_ciudad: "IQUIRA", codigo_departamento: 41 },
  { codigo_ciudad: 41359, nombre_ciudad: "ISNOS", codigo_departamento: 41 },
  {
    codigo_ciudad: 41378,
    nombre_ciudad: "LA ARGENTINA",
    codigo_departamento: 41,
  },
  { codigo_ciudad: 41396, nombre_ciudad: "LA PLATA", codigo_departamento: 41 },
  { codigo_ciudad: 41483, nombre_ciudad: "NATAGA", codigo_departamento: 41 },
  { codigo_ciudad: 41503, nombre_ciudad: "OPORAPA", codigo_departamento: 41 },
  { codigo_ciudad: 41518, nombre_ciudad: "PAICOL", codigo_departamento: 41 },
  { codigo_ciudad: 41524, nombre_ciudad: "PALERMO", codigo_departamento: 41 },
  { codigo_ciudad: 41530, nombre_ciudad: "PALESTINA", codigo_departamento: 41 },
  { codigo_ciudad: 41548, nombre_ciudad: "PITAL", codigo_departamento: 41 },
  { codigo_ciudad: 41551, nombre_ciudad: "PITALITO", codigo_departamento: 41 },
  { codigo_ciudad: 41615, nombre_ciudad: "RIVERA", codigo_departamento: 41 },
  {
    codigo_ciudad: 41660,
    nombre_ciudad: "SALADOBLANCO",
    codigo_departamento: 41,
  },
  {
    codigo_ciudad: 41668,
    nombre_ciudad: "SAN AGUSTIN",
    codigo_departamento: 41,
  },
  {
    codigo_ciudad: 41676,
    nombre_ciudad: "SANTA MARIA",
    codigo_departamento: 41,
  },
  { codigo_ciudad: 41770, nombre_ciudad: "SUAZA", codigo_departamento: 41 },
  { codigo_ciudad: 41791, nombre_ciudad: "TARQUI", codigo_departamento: 41 },
  { codigo_ciudad: 41797, nombre_ciudad: "TESALIA", codigo_departamento: 41 },
  { codigo_ciudad: 41799, nombre_ciudad: "TELLO", codigo_departamento: 41 },
  { codigo_ciudad: 41801, nombre_ciudad: "TERUEL", codigo_departamento: 41 },
  { codigo_ciudad: 41807, nombre_ciudad: "TIMANA", codigo_departamento: 41 },
  {
    codigo_ciudad: 41872,
    nombre_ciudad: "VILLAVIEJA",
    codigo_departamento: 41,
  },
  { codigo_ciudad: 41885, nombre_ciudad: "YAGUARA", codigo_departamento: 41 },
  { codigo_ciudad: 44001, nombre_ciudad: "RIOHACHA", codigo_departamento: 44 },
  { codigo_ciudad: 44035, nombre_ciudad: "ALBANIA", codigo_departamento: 44 },
  { codigo_ciudad: 44078, nombre_ciudad: "BARRANCAS", codigo_departamento: 44 },
  { codigo_ciudad: 44090, nombre_ciudad: "DIBULLA", codigo_departamento: 44 },
  {
    codigo_ciudad: 44098,
    nombre_ciudad: "DISTRACCION",
    codigo_departamento: 44,
  },
  { codigo_ciudad: 44110, nombre_ciudad: "EL MOLINO", codigo_departamento: 44 },
  { codigo_ciudad: 44279, nombre_ciudad: "FONSECA", codigo_departamento: 44 },
  { codigo_ciudad: 44378, nombre_ciudad: "HATONUEVO", codigo_departamento: 44 },
  {
    codigo_ciudad: 44420,
    nombre_ciudad: "LA JAGUA DEL PILAR",
    codigo_departamento: 44,
  },
  { codigo_ciudad: 44430, nombre_ciudad: "MAICAO", codigo_departamento: 44 },
  { codigo_ciudad: 44560, nombre_ciudad: "MANAURE", codigo_departamento: 44 },
  {
    codigo_ciudad: 44650,
    nombre_ciudad: "SAN JUAN DEL CESAR",
    codigo_departamento: 44,
  },
  { codigo_ciudad: 44847, nombre_ciudad: "URIBIA", codigo_departamento: 44 },
  { codigo_ciudad: 44855, nombre_ciudad: "URUMITA", codigo_departamento: 44 },
  {
    codigo_ciudad: 44874,
    nombre_ciudad: "VILLANUEVA",
    codigo_departamento: 44,
  },
  {
    codigo_ciudad: 47001,
    nombre_ciudad: "SANTA MARTA",
    codigo_departamento: 47,
  },
  { codigo_ciudad: 47030, nombre_ciudad: "ALGARROBO", codigo_departamento: 47 },
  { codigo_ciudad: 47053, nombre_ciudad: "ARACATACA", codigo_departamento: 47 },
  { codigo_ciudad: 47058, nombre_ciudad: "ARIGUANI", codigo_departamento: 47 },
  {
    codigo_ciudad: 47161,
    nombre_ciudad: "CERRO DE SAN ANTONIO",
    codigo_departamento: 47,
  },
  { codigo_ciudad: 47170, nombre_ciudad: "CHIVOLO", codigo_departamento: 47 },
  { codigo_ciudad: 47189, nombre_ciudad: "CIENAGA", codigo_departamento: 47 },
  { codigo_ciudad: 47205, nombre_ciudad: "CONCORDIA", codigo_departamento: 47 },
  { codigo_ciudad: 47245, nombre_ciudad: "EL BANCO", codigo_departamento: 47 },
  { codigo_ciudad: 47258, nombre_ciudad: "EL PIÑON", codigo_departamento: 47 },
  { codigo_ciudad: 47268, nombre_ciudad: "EL RETEN", codigo_departamento: 47 },
  { codigo_ciudad: 47288, nombre_ciudad: "FUNDACION", codigo_departamento: 47 },
  { codigo_ciudad: 47318, nombre_ciudad: "GUAMAL", codigo_departamento: 47 },
  {
    codigo_ciudad: 47460,
    nombre_ciudad: "NUEVA GRANADA",
    codigo_departamento: 47,
  },
  { codigo_ciudad: 47541, nombre_ciudad: "PEDRAZA", codigo_departamento: 47 },
  {
    codigo_ciudad: 47545,
    nombre_ciudad: "PIJIÑO DEL CARMEN",
    codigo_departamento: 47,
  },
  { codigo_ciudad: 47551, nombre_ciudad: "PIVIJAY", codigo_departamento: 47 },
  { codigo_ciudad: 47555, nombre_ciudad: "PLATO", codigo_departamento: 47 },
  {
    codigo_ciudad: 47570,
    nombre_ciudad: "PUEBLOVIEJO",
    codigo_departamento: 47,
  },
  { codigo_ciudad: 47605, nombre_ciudad: "REMOLINO", codigo_departamento: 47 },
  {
    codigo_ciudad: 47660,
    nombre_ciudad: "SABANAS DE SAN ANGEL",
    codigo_departamento: 47,
  },
  { codigo_ciudad: 47675, nombre_ciudad: "SALAMINA", codigo_departamento: 47 },
  {
    codigo_ciudad: 47692,
    nombre_ciudad: "SAN SEBASTIAN DE BUENAVISTA",
    codigo_departamento: 47,
  },
  { codigo_ciudad: 47703, nombre_ciudad: "SAN ZENON", codigo_departamento: 47 },
  { codigo_ciudad: 47707, nombre_ciudad: "SANTA ANA", codigo_departamento: 47 },
  {
    codigo_ciudad: 47720,
    nombre_ciudad: "SANTA BARBARA DE PINTO",
    codigo_departamento: 47,
  },
  {
    codigo_ciudad: 47745,
    nombre_ciudad: "SITIONUEVO",
    codigo_departamento: 47,
  },
  { codigo_ciudad: 47798, nombre_ciudad: "TENERIFE", codigo_departamento: 47 },
  { codigo_ciudad: 47960, nombre_ciudad: "ZAPAYAN", codigo_departamento: 47 },
  {
    codigo_ciudad: 47980,
    nombre_ciudad: "ZONA BANANERA",
    codigo_departamento: 47,
  },
  {
    codigo_ciudad: 50001,
    nombre_ciudad: "VILLAVICENCIO",
    codigo_departamento: 50,
  },
  { codigo_ciudad: 50006, nombre_ciudad: "ACACIAS", codigo_departamento: 50 },
  {
    codigo_ciudad: 50110,
    nombre_ciudad: "BARRANCA DE UPIA",
    codigo_departamento: 50,
  },
  { codigo_ciudad: 50124, nombre_ciudad: "CABUYARO", codigo_departamento: 50 },
  {
    codigo_ciudad: 50150,
    nombre_ciudad: "CASTILLA LA NUEVA",
    codigo_departamento: 50,
  },
  { codigo_ciudad: 50223, nombre_ciudad: "CUBARRAL", codigo_departamento: 50 },
  { codigo_ciudad: 50226, nombre_ciudad: "CUMARAL", codigo_departamento: 50 },
  {
    codigo_ciudad: 50245,
    nombre_ciudad: "EL CALVARIO",
    codigo_departamento: 50,
  },
  {
    codigo_ciudad: 50251,
    nombre_ciudad: "EL CASTILLO",
    codigo_departamento: 50,
  },
  { codigo_ciudad: 50270, nombre_ciudad: "EL DORADO", codigo_departamento: 50 },
  {
    codigo_ciudad: 50287,
    nombre_ciudad: "FUENTE DE ORO",
    codigo_departamento: 50,
  },
  { codigo_ciudad: 50313, nombre_ciudad: "GRANADA", codigo_departamento: 50 },
  { codigo_ciudad: 50318, nombre_ciudad: "GUAMAL", codigo_departamento: 50 },
  { codigo_ciudad: 50325, nombre_ciudad: "MAPIRIPAN", codigo_departamento: 50 },
  { codigo_ciudad: 50330, nombre_ciudad: "MESETAS", codigo_departamento: 50 },
  {
    codigo_ciudad: 50350,
    nombre_ciudad: "LA MACARENA",
    codigo_departamento: 50,
  },
  { codigo_ciudad: 50370, nombre_ciudad: "URIBE", codigo_departamento: 50 },
  { codigo_ciudad: 50400, nombre_ciudad: "LEJANIAS", codigo_departamento: 50 },
  {
    codigo_ciudad: 50450,
    nombre_ciudad: "PUERTO CONCORDIA",
    codigo_departamento: 50,
  },
  {
    codigo_ciudad: 50568,
    nombre_ciudad: "PUERTO GAITAN",
    codigo_departamento: 50,
  },
  {
    codigo_ciudad: 50573,
    nombre_ciudad: "PUERTO LOPEZ",
    codigo_departamento: 50,
  },
  {
    codigo_ciudad: 50577,
    nombre_ciudad: "PUERTO LLERAS",
    codigo_departamento: 50,
  },
  {
    codigo_ciudad: 50590,
    nombre_ciudad: "PUERTO RICO",
    codigo_departamento: 50,
  },
  { codigo_ciudad: 50606, nombre_ciudad: "RESTREPO", codigo_departamento: 50 },
  {
    codigo_ciudad: 50680,
    nombre_ciudad: "SAN CARLOS DE GUAROA",
    codigo_departamento: 50,
  },
  {
    codigo_ciudad: 50683,
    nombre_ciudad: "SAN JUAN DE ARAMA",
    codigo_departamento: 50,
  },
  {
    codigo_ciudad: 50686,
    nombre_ciudad: "SAN JUANITO",
    codigo_departamento: 50,
  },
  {
    codigo_ciudad: 50689,
    nombre_ciudad: "SAN MARTIN",
    codigo_departamento: 50,
  },
  {
    codigo_ciudad: 50711,
    nombre_ciudad: "VISTAHERMOSA",
    codigo_departamento: 50,
  },
  { codigo_ciudad: 52001, nombre_ciudad: "PASTO", codigo_departamento: 52 },
  { codigo_ciudad: 52019, nombre_ciudad: "ALBAN", codigo_departamento: 52 },
  { codigo_ciudad: 52022, nombre_ciudad: "ALDANA", codigo_departamento: 52 },
  { codigo_ciudad: 52036, nombre_ciudad: "ANCUYA", codigo_departamento: 52 },
  { codigo_ciudad: 52051, nombre_ciudad: "ARBOLEDA", codigo_departamento: 52 },
  { codigo_ciudad: 52079, nombre_ciudad: "BARBACOAS", codigo_departamento: 52 },
  { codigo_ciudad: 52083, nombre_ciudad: "BELEN", codigo_departamento: 52 },
  { codigo_ciudad: 52110, nombre_ciudad: "BUESACO", codigo_departamento: 52 },
  { codigo_ciudad: 52203, nombre_ciudad: "COLON", codigo_departamento: 52 },
  { codigo_ciudad: 52207, nombre_ciudad: "CONSACA", codigo_departamento: 52 },
  { codigo_ciudad: 52210, nombre_ciudad: "CONTADERO", codigo_departamento: 52 },
  { codigo_ciudad: 52215, nombre_ciudad: "CORDOBA", codigo_departamento: 52 },
  {
    codigo_ciudad: 52224,
    nombre_ciudad: "CUASPUD CARLOSAMA",
    codigo_departamento: 52,
  },
  { codigo_ciudad: 52227, nombre_ciudad: "CUMBAL", codigo_departamento: 52 },
  { codigo_ciudad: 52233, nombre_ciudad: "CUMBITARA", codigo_departamento: 52 },
  { codigo_ciudad: 52240, nombre_ciudad: "CHACHAGÜI", codigo_departamento: 52 },
  { codigo_ciudad: 52250, nombre_ciudad: "EL CHARCO", codigo_departamento: 52 },
  { codigo_ciudad: 52254, nombre_ciudad: "EL PEÑOL", codigo_departamento: 52 },
  {
    codigo_ciudad: 52256,
    nombre_ciudad: "EL ROSARIO",
    codigo_departamento: 52,
  },
  {
    codigo_ciudad: 52258,
    nombre_ciudad: "EL TABLON DE GOMEZ",
    codigo_departamento: 52,
  },
  { codigo_ciudad: 52260, nombre_ciudad: "EL TAMBO", codigo_departamento: 52 },
  { codigo_ciudad: 52287, nombre_ciudad: "FUNES", codigo_departamento: 52 },
  { codigo_ciudad: 52317, nombre_ciudad: "GUACHUCAL", codigo_departamento: 52 },
  {
    codigo_ciudad: 52320,
    nombre_ciudad: "GUAITARILLA",
    codigo_departamento: 52,
  },
  { codigo_ciudad: 52323, nombre_ciudad: "GUALMATAN", codigo_departamento: 52 },
  { codigo_ciudad: 52352, nombre_ciudad: "ILES", codigo_departamento: 52 },
  { codigo_ciudad: 52354, nombre_ciudad: "IMUES", codigo_departamento: 52 },
  { codigo_ciudad: 52356, nombre_ciudad: "IPIALES", codigo_departamento: 52 },
  { codigo_ciudad: 52378, nombre_ciudad: "LA CRUZ", codigo_departamento: 52 },
  {
    codigo_ciudad: 52381,
    nombre_ciudad: "LA FLORIDA",
    codigo_departamento: 52,
  },
  {
    codigo_ciudad: 52385,
    nombre_ciudad: "LA LLANADA",
    codigo_departamento: 52,
  },
  { codigo_ciudad: 52390, nombre_ciudad: "LA TOLA", codigo_departamento: 52 },
  { codigo_ciudad: 52399, nombre_ciudad: "LA UNION", codigo_departamento: 52 },
  { codigo_ciudad: 52405, nombre_ciudad: "LEIVA", codigo_departamento: 52 },
  { codigo_ciudad: 52411, nombre_ciudad: "LINARES", codigo_departamento: 52 },
  { codigo_ciudad: 52418, nombre_ciudad: "LOS ANDES", codigo_departamento: 52 },
  { codigo_ciudad: 52427, nombre_ciudad: "MAGÜI", codigo_departamento: 52 },
  { codigo_ciudad: 52435, nombre_ciudad: "MALLAMA", codigo_departamento: 52 },
  { codigo_ciudad: 52473, nombre_ciudad: "MOSQUERA", codigo_departamento: 52 },
  { codigo_ciudad: 52480, nombre_ciudad: "NARIÑO", codigo_departamento: 52 },
  {
    codigo_ciudad: 52490,
    nombre_ciudad: "OLAYA HERRERA",
    codigo_departamento: 52,
  },
  { codigo_ciudad: 52506, nombre_ciudad: "OSPINA", codigo_departamento: 52 },
  {
    codigo_ciudad: 52520,
    nombre_ciudad: "FRANCISCO PIZARRO",
    codigo_departamento: 52,
  },
  { codigo_ciudad: 52540, nombre_ciudad: "POLICARPA", codigo_departamento: 52 },
  { codigo_ciudad: 52560, nombre_ciudad: "POTOSI", codigo_departamento: 52 },
  {
    codigo_ciudad: 52565,
    nombre_ciudad: "PROVIDENCIA",
    codigo_departamento: 52,
  },
  { codigo_ciudad: 52573, nombre_ciudad: "PUERRES", codigo_departamento: 52 },
  { codigo_ciudad: 52585, nombre_ciudad: "PUPIALES", codigo_departamento: 52 },
  { codigo_ciudad: 52612, nombre_ciudad: "RICAURTE", codigo_departamento: 52 },
  {
    codigo_ciudad: 52621,
    nombre_ciudad: "ROBERTO PAYAN",
    codigo_departamento: 52,
  },
  { codigo_ciudad: 52678, nombre_ciudad: "SAMANIEGO", codigo_departamento: 52 },
  { codigo_ciudad: 52683, nombre_ciudad: "SANDONA", codigo_departamento: 52 },
  {
    codigo_ciudad: 52685,
    nombre_ciudad: "SAN BERNARDO",
    codigo_departamento: 52,
  },
  {
    codigo_ciudad: 52687,
    nombre_ciudad: "SAN LORENZO",
    codigo_departamento: 52,
  },
  { codigo_ciudad: 52693, nombre_ciudad: "SAN PABLO", codigo_departamento: 52 },
  {
    codigo_ciudad: 52694,
    nombre_ciudad: "SAN PEDRO DE CARTAGO",
    codigo_departamento: 52,
  },
  {
    codigo_ciudad: 52696,
    nombre_ciudad: "SANTA BARBARA",
    codigo_departamento: 52,
  },
  { codigo_ciudad: 52699, nombre_ciudad: "SANTACRUZ", codigo_departamento: 52 },
  { codigo_ciudad: 52720, nombre_ciudad: "SAPUYES", codigo_departamento: 52 },
  { codigo_ciudad: 52786, nombre_ciudad: "TAMINANGO", codigo_departamento: 52 },
  { codigo_ciudad: 52788, nombre_ciudad: "TANGUA", codigo_departamento: 52 },
  {
    codigo_ciudad: 52835,
    nombre_ciudad: "SAN ANDRES DE TUMACO",
    codigo_departamento: 52,
  },
  { codigo_ciudad: 52838, nombre_ciudad: "TUQUERRES", codigo_departamento: 52 },
  {
    codigo_ciudad: 52885,
    nombre_ciudad: "YACUANQUER",
    codigo_departamento: 52,
  },
  {
    codigo_ciudad: 54001,
    nombre_ciudad: "SAN JOSE DE CUCUTA",
    codigo_departamento: 54,
  },
  { codigo_ciudad: 54003, nombre_ciudad: "ABREGO", codigo_departamento: 54 },
  { codigo_ciudad: 54051, nombre_ciudad: "ARBOLEDAS", codigo_departamento: 54 },
  { codigo_ciudad: 54099, nombre_ciudad: "BOCHALEMA", codigo_departamento: 54 },
  {
    codigo_ciudad: 54109,
    nombre_ciudad: "BUCARASICA",
    codigo_departamento: 54,
  },
  { codigo_ciudad: 54125, nombre_ciudad: "CACOTA", codigo_departamento: 54 },
  { codigo_ciudad: 54128, nombre_ciudad: "CACHIRA", codigo_departamento: 54 },
  { codigo_ciudad: 54172, nombre_ciudad: "CHINACOTA", codigo_departamento: 54 },
  { codigo_ciudad: 54174, nombre_ciudad: "CHITAGA", codigo_departamento: 54 },
  {
    codigo_ciudad: 54206,
    nombre_ciudad: "CONVENCION",
    codigo_departamento: 54,
  },
  { codigo_ciudad: 54223, nombre_ciudad: "CUCUTILLA", codigo_departamento: 54 },
  { codigo_ciudad: 54239, nombre_ciudad: "DURANIA", codigo_departamento: 54 },
  { codigo_ciudad: 54245, nombre_ciudad: "EL CARMEN", codigo_departamento: 54 },
  { codigo_ciudad: 54250, nombre_ciudad: "EL TARRA", codigo_departamento: 54 },
  { codigo_ciudad: 54261, nombre_ciudad: "EL ZULIA", codigo_departamento: 54 },
  { codigo_ciudad: 54313, nombre_ciudad: "GRAMALOTE", codigo_departamento: 54 },
  { codigo_ciudad: 54344, nombre_ciudad: "HACARI", codigo_departamento: 54 },
  { codigo_ciudad: 54347, nombre_ciudad: "HERRAN", codigo_departamento: 54 },
  { codigo_ciudad: 54377, nombre_ciudad: "LABATECA", codigo_departamento: 54 },
  {
    codigo_ciudad: 54385,
    nombre_ciudad: "LA ESPERANZA",
    codigo_departamento: 54,
  },
  { codigo_ciudad: 54398, nombre_ciudad: "LA PLAYA", codigo_departamento: 54 },
  {
    codigo_ciudad: 54405,
    nombre_ciudad: "LOS PATIOS",
    codigo_departamento: 54,
  },
  { codigo_ciudad: 54418, nombre_ciudad: "LOURDES", codigo_departamento: 54 },
  { codigo_ciudad: 54480, nombre_ciudad: "MUTISCUA", codigo_departamento: 54 },
  { codigo_ciudad: 54498, nombre_ciudad: "OCAÑA", codigo_departamento: 54 },
  { codigo_ciudad: 54518, nombre_ciudad: "PAMPLONA", codigo_departamento: 54 },
  {
    codigo_ciudad: 54520,
    nombre_ciudad: "PAMPLONITA",
    codigo_departamento: 54,
  },
  {
    codigo_ciudad: 54553,
    nombre_ciudad: "PUERTO SANTANDER",
    codigo_departamento: 54,
  },
  {
    codigo_ciudad: 54599,
    nombre_ciudad: "RAGONVALIA",
    codigo_departamento: 54,
  },
  { codigo_ciudad: 54660, nombre_ciudad: "SALAZAR", codigo_departamento: 54 },
  {
    codigo_ciudad: 54670,
    nombre_ciudad: "SAN CALIXTO",
    codigo_departamento: 54,
  },
  {
    codigo_ciudad: 54673,
    nombre_ciudad: "SAN CAYETANO",
    codigo_departamento: 54,
  },
  { codigo_ciudad: 54680, nombre_ciudad: "SANTIAGO", codigo_departamento: 54 },
  { codigo_ciudad: 54720, nombre_ciudad: "SARDINATA", codigo_departamento: 54 },
  { codigo_ciudad: 54743, nombre_ciudad: "SILOS", codigo_departamento: 54 },
  { codigo_ciudad: 54800, nombre_ciudad: "TEORAMA", codigo_departamento: 54 },
  { codigo_ciudad: 54810, nombre_ciudad: "TIBU", codigo_departamento: 54 },
  { codigo_ciudad: 54820, nombre_ciudad: "TOLEDO", codigo_departamento: 54 },
  {
    codigo_ciudad: 54871,
    nombre_ciudad: "VILLA CARO",
    codigo_departamento: 54,
  },
  {
    codigo_ciudad: 54874,
    nombre_ciudad: "VILLA DEL ROSARIO",
    codigo_departamento: 54,
  },
  { codigo_ciudad: 63001, nombre_ciudad: "ARMENIA", codigo_departamento: 63 },
  {
    codigo_ciudad: 63111,
    nombre_ciudad: "BUENAVISTA",
    codigo_departamento: 63,
  },
  { codigo_ciudad: 63130, nombre_ciudad: "CALARCA", codigo_departamento: 63 },
  { codigo_ciudad: 63190, nombre_ciudad: "CIRCASIA", codigo_departamento: 63 },
  { codigo_ciudad: 63212, nombre_ciudad: "CORDOBA", codigo_departamento: 63 },
  { codigo_ciudad: 63272, nombre_ciudad: "FILANDIA", codigo_departamento: 63 },
  { codigo_ciudad: 63302, nombre_ciudad: "GENOVA", codigo_departamento: 63 },
  {
    codigo_ciudad: 63401,
    nombre_ciudad: "LA TEBAIDA",
    codigo_departamento: 63,
  },
  {
    codigo_ciudad: 63470,
    nombre_ciudad: "MONTENEGRO",
    codigo_departamento: 63,
  },
  { codigo_ciudad: 63548, nombre_ciudad: "PIJAO", codigo_departamento: 63 },
  { codigo_ciudad: 63594, nombre_ciudad: "QUIMBAYA", codigo_departamento: 63 },
  { codigo_ciudad: 63690, nombre_ciudad: "SALENTO", codigo_departamento: 63 },
  { codigo_ciudad: 66001, nombre_ciudad: "PEREIRA", codigo_departamento: 66 },
  { codigo_ciudad: 66045, nombre_ciudad: "APIA", codigo_departamento: 66 },
  { codigo_ciudad: 66075, nombre_ciudad: "BALBOA", codigo_departamento: 66 },
  {
    codigo_ciudad: 66088,
    nombre_ciudad: "BELEN DE UMBRIA",
    codigo_departamento: 66,
  },
  {
    codigo_ciudad: 66170,
    nombre_ciudad: "DOSQUEBRADAS",
    codigo_departamento: 66,
  },
  { codigo_ciudad: 66318, nombre_ciudad: "GUATICA", codigo_departamento: 66 },
  { codigo_ciudad: 66383, nombre_ciudad: "LA CELIA", codigo_departamento: 66 },
  {
    codigo_ciudad: 66400,
    nombre_ciudad: "LA VIRGINIA",
    codigo_departamento: 66,
  },
  { codigo_ciudad: 66440, nombre_ciudad: "MARSELLA", codigo_departamento: 66 },
  { codigo_ciudad: 66456, nombre_ciudad: "MISTRATO", codigo_departamento: 66 },
  {
    codigo_ciudad: 66572,
    nombre_ciudad: "PUEBLO RICO",
    codigo_departamento: 66,
  },
  { codigo_ciudad: 66594, nombre_ciudad: "QUINCHIA", codigo_departamento: 66 },
  {
    codigo_ciudad: 66682,
    nombre_ciudad: "SANTA ROSA DE CABAL",
    codigo_departamento: 66,
  },
  { codigo_ciudad: 66687, nombre_ciudad: "SANTUARIO", codigo_departamento: 66 },
  {
    codigo_ciudad: 68001,
    nombre_ciudad: "BUCARAMANGA",
    codigo_departamento: 68,
  },
  { codigo_ciudad: 68013, nombre_ciudad: "AGUADA", codigo_departamento: 68 },
  { codigo_ciudad: 68020, nombre_ciudad: "ALBANIA", codigo_departamento: 68 },
  { codigo_ciudad: 68051, nombre_ciudad: "ARATOCA", codigo_departamento: 68 },
  { codigo_ciudad: 68077, nombre_ciudad: "BARBOSA", codigo_departamento: 68 },
  { codigo_ciudad: 68079, nombre_ciudad: "BARICHARA", codigo_departamento: 68 },
  {
    codigo_ciudad: 68081,
    nombre_ciudad: "BARRANCABERMEJA",
    codigo_departamento: 68,
  },
  { codigo_ciudad: 68092, nombre_ciudad: "BETULIA", codigo_departamento: 68 },
  { codigo_ciudad: 68101, nombre_ciudad: "BOLIVAR", codigo_departamento: 68 },
  { codigo_ciudad: 68121, nombre_ciudad: "CABRERA", codigo_departamento: 68 },
  {
    codigo_ciudad: 68132,
    nombre_ciudad: "CALIFORNIA",
    codigo_departamento: 68,
  },
  {
    codigo_ciudad: 68147,
    nombre_ciudad: "CAPITANEJO",
    codigo_departamento: 68,
  },
  { codigo_ciudad: 68152, nombre_ciudad: "CARCASI", codigo_departamento: 68 },
  { codigo_ciudad: 68160, nombre_ciudad: "CEPITA", codigo_departamento: 68 },
  { codigo_ciudad: 68162, nombre_ciudad: "CERRITO", codigo_departamento: 68 },
  { codigo_ciudad: 68167, nombre_ciudad: "CHARALA", codigo_departamento: 68 },
  { codigo_ciudad: 68169, nombre_ciudad: "CHARTA", codigo_departamento: 68 },
  { codigo_ciudad: 68176, nombre_ciudad: "CHIMA", codigo_departamento: 68 },
  { codigo_ciudad: 68179, nombre_ciudad: "CHIPATA", codigo_departamento: 68 },
  { codigo_ciudad: 68190, nombre_ciudad: "CIMITARRA", codigo_departamento: 68 },
  {
    codigo_ciudad: 68207,
    nombre_ciudad: "CONCEPCION",
    codigo_departamento: 68,
  },
  { codigo_ciudad: 68209, nombre_ciudad: "CONFINES", codigo_departamento: 68 },
  {
    codigo_ciudad: 68211,
    nombre_ciudad: "CONTRATACION",
    codigo_departamento: 68,
  },
  { codigo_ciudad: 68217, nombre_ciudad: "COROMORO", codigo_departamento: 68 },
  { codigo_ciudad: 68229, nombre_ciudad: "CURITI", codigo_departamento: 68 },
  {
    codigo_ciudad: 68235,
    nombre_ciudad: "EL CARMEN DE CHUCURI",
    codigo_departamento: 68,
  },
  {
    codigo_ciudad: 68245,
    nombre_ciudad: "EL GUACAMAYO",
    codigo_departamento: 68,
  },
  { codigo_ciudad: 68250, nombre_ciudad: "EL PEÑON", codigo_departamento: 68 },
  { codigo_ciudad: 68255, nombre_ciudad: "EL PLAYON", codigo_departamento: 68 },
  { codigo_ciudad: 68264, nombre_ciudad: "ENCINO", codigo_departamento: 68 },
  { codigo_ciudad: 68266, nombre_ciudad: "ENCISO", codigo_departamento: 68 },
  { codigo_ciudad: 68271, nombre_ciudad: "FLORIAN", codigo_departamento: 68 },
  {
    codigo_ciudad: 68276,
    nombre_ciudad: "FLORIDABLANCA",
    codigo_departamento: 68,
  },
  { codigo_ciudad: 68296, nombre_ciudad: "GALAN", codigo_departamento: 68 },
  { codigo_ciudad: 68298, nombre_ciudad: "GAMBITA", codigo_departamento: 68 },
  { codigo_ciudad: 68307, nombre_ciudad: "GIRON", codigo_departamento: 68 },
  { codigo_ciudad: 68318, nombre_ciudad: "GUACA", codigo_departamento: 68 },
  { codigo_ciudad: 68320, nombre_ciudad: "GUADALUPE", codigo_departamento: 68 },
  { codigo_ciudad: 68322, nombre_ciudad: "GUAPOTA", codigo_departamento: 68 },
  { codigo_ciudad: 68324, nombre_ciudad: "GUAVATA", codigo_departamento: 68 },
  { codigo_ciudad: 68327, nombre_ciudad: "GÜEPSA", codigo_departamento: 68 },
  { codigo_ciudad: 68344, nombre_ciudad: "HATO", codigo_departamento: 68 },
  {
    codigo_ciudad: 68368,
    nombre_ciudad: "JESUS MARIA",
    codigo_departamento: 68,
  },
  { codigo_ciudad: 68370, nombre_ciudad: "JORDAN", codigo_departamento: 68 },
  {
    codigo_ciudad: 68377,
    nombre_ciudad: "LA BELLEZA",
    codigo_departamento: 68,
  },
  { codigo_ciudad: 68385, nombre_ciudad: "LANDAZURI", codigo_departamento: 68 },
  { codigo_ciudad: 68397, nombre_ciudad: "LA PAZ", codigo_departamento: 68 },
  { codigo_ciudad: 68406, nombre_ciudad: "LEBRIJA", codigo_departamento: 68 },
  {
    codigo_ciudad: 68418,
    nombre_ciudad: "LOS SANTOS",
    codigo_departamento: 68,
  },
  {
    codigo_ciudad: 68425,
    nombre_ciudad: "MACARAVITA",
    codigo_departamento: 68,
  },
  { codigo_ciudad: 68432, nombre_ciudad: "MALAGA", codigo_departamento: 68 },
  { codigo_ciudad: 68444, nombre_ciudad: "MATANZA", codigo_departamento: 68 },
  { codigo_ciudad: 68464, nombre_ciudad: "MOGOTES", codigo_departamento: 68 },
  {
    codigo_ciudad: 68468,
    nombre_ciudad: "MOLAGAVITA",
    codigo_departamento: 68,
  },
  { codigo_ciudad: 68498, nombre_ciudad: "OCAMONTE", codigo_departamento: 68 },
  { codigo_ciudad: 68500, nombre_ciudad: "OIBA", codigo_departamento: 68 },
  { codigo_ciudad: 68502, nombre_ciudad: "ONZAGA", codigo_departamento: 68 },
  { codigo_ciudad: 68522, nombre_ciudad: "PALMAR", codigo_departamento: 68 },
  {
    codigo_ciudad: 68524,
    nombre_ciudad: "PALMAS DEL SOCORRO",
    codigo_departamento: 68,
  },
  { codigo_ciudad: 68533, nombre_ciudad: "PARAMO", codigo_departamento: 68 },
  {
    codigo_ciudad: 68547,
    nombre_ciudad: "PIEDECUESTA",
    codigo_departamento: 68,
  },
  { codigo_ciudad: 68549, nombre_ciudad: "PINCHOTE", codigo_departamento: 68 },
  {
    codigo_ciudad: 68572,
    nombre_ciudad: "PUENTE NACIONAL",
    codigo_departamento: 68,
  },
  {
    codigo_ciudad: 68573,
    nombre_ciudad: "PUERTO PARRA",
    codigo_departamento: 68,
  },
  {
    codigo_ciudad: 68575,
    nombre_ciudad: "PUERTO WILCHES",
    codigo_departamento: 68,
  },
  { codigo_ciudad: 68615, nombre_ciudad: "RIONEGRO", codigo_departamento: 68 },
  {
    codigo_ciudad: 68655,
    nombre_ciudad: "SABANA DE TORRES",
    codigo_departamento: 68,
  },
  {
    codigo_ciudad: 68669,
    nombre_ciudad: "SAN ANDRES",
    codigo_departamento: 68,
  },
  {
    codigo_ciudad: 68673,
    nombre_ciudad: "SAN BENITO",
    codigo_departamento: 68,
  },
  { codigo_ciudad: 68679, nombre_ciudad: "SAN GIL", codigo_departamento: 68 },
  {
    codigo_ciudad: 68682,
    nombre_ciudad: "SAN JOAQUIN",
    codigo_departamento: 68,
  },
  {
    codigo_ciudad: 68684,
    nombre_ciudad: "SAN JOSE DE MIRANDA",
    codigo_departamento: 68,
  },
  {
    codigo_ciudad: 68686,
    nombre_ciudad: "SAN MIGUEL",
    codigo_departamento: 68,
  },
  {
    codigo_ciudad: 68689,
    nombre_ciudad: "SAN VICENTE DE CHUCURI",
    codigo_departamento: 68,
  },
  {
    codigo_ciudad: 68705,
    nombre_ciudad: "SANTA BARBARA",
    codigo_departamento: 68,
  },
  {
    codigo_ciudad: 68720,
    nombre_ciudad: "SANTA HELENA DEL OPON",
    codigo_departamento: 68,
  },
  { codigo_ciudad: 68745, nombre_ciudad: "SIMACOTA", codigo_departamento: 68 },
  { codigo_ciudad: 68755, nombre_ciudad: "SOCORRO", codigo_departamento: 68 },
  { codigo_ciudad: 68770, nombre_ciudad: "SUAITA", codigo_departamento: 68 },
  { codigo_ciudad: 68773, nombre_ciudad: "SUCRE", codigo_departamento: 68 },
  { codigo_ciudad: 68780, nombre_ciudad: "SURATA", codigo_departamento: 68 },
  { codigo_ciudad: 68820, nombre_ciudad: "TONA", codigo_departamento: 68 },
  {
    codigo_ciudad: 68855,
    nombre_ciudad: "VALLE DE SAN JOSE",
    codigo_departamento: 68,
  },
  { codigo_ciudad: 68861, nombre_ciudad: "VELEZ", codigo_departamento: 68 },
  { codigo_ciudad: 68867, nombre_ciudad: "VETAS", codigo_departamento: 68 },
  {
    codigo_ciudad: 68872,
    nombre_ciudad: "VILLANUEVA",
    codigo_departamento: 68,
  },
  { codigo_ciudad: 68895, nombre_ciudad: "ZAPATOCA", codigo_departamento: 68 },
  { codigo_ciudad: 70001, nombre_ciudad: "SINCELEJO", codigo_departamento: 70 },
  {
    codigo_ciudad: 70110,
    nombre_ciudad: "BUENAVISTA",
    codigo_departamento: 70,
  },
  { codigo_ciudad: 70124, nombre_ciudad: "CAIMITO", codigo_departamento: 70 },
  { codigo_ciudad: 70204, nombre_ciudad: "COLOSO", codigo_departamento: 70 },
  { codigo_ciudad: 70215, nombre_ciudad: "COROZAL", codigo_departamento: 70 },
  { codigo_ciudad: 70221, nombre_ciudad: "COVEÑAS", codigo_departamento: 70 },
  { codigo_ciudad: 70230, nombre_ciudad: "CHALAN", codigo_departamento: 70 },
  { codigo_ciudad: 70233, nombre_ciudad: "EL ROBLE", codigo_departamento: 70 },
  { codigo_ciudad: 70235, nombre_ciudad: "GALERAS", codigo_departamento: 70 },
  { codigo_ciudad: 70265, nombre_ciudad: "GUARANDA", codigo_departamento: 70 },
  { codigo_ciudad: 70400, nombre_ciudad: "LA UNION", codigo_departamento: 70 },
  {
    codigo_ciudad: 70418,
    nombre_ciudad: "LOS PALMITOS",
    codigo_departamento: 70,
  },
  { codigo_ciudad: 70429, nombre_ciudad: "MAJAGUAL", codigo_departamento: 70 },
  { codigo_ciudad: 70473, nombre_ciudad: "MORROA", codigo_departamento: 70 },
  { codigo_ciudad: 70508, nombre_ciudad: "OVEJAS", codigo_departamento: 70 },
  { codigo_ciudad: 70523, nombre_ciudad: "PALMITO", codigo_departamento: 70 },
  { codigo_ciudad: 70670, nombre_ciudad: "SAMPUES", codigo_departamento: 70 },
  {
    codigo_ciudad: 70678,
    nombre_ciudad: "SAN BENITO ABAD",
    codigo_departamento: 70,
  },
  {
    codigo_ciudad: 70702,
    nombre_ciudad: "SAN JUAN DE BETULIA",
    codigo_departamento: 70,
  },
  {
    codigo_ciudad: 70708,
    nombre_ciudad: "SAN MARCOS",
    codigo_departamento: 70,
  },
  {
    codigo_ciudad: 70713,
    nombre_ciudad: "SAN ONOFRE",
    codigo_departamento: 70,
  },
  { codigo_ciudad: 70717, nombre_ciudad: "SAN PEDRO", codigo_departamento: 70 },
  {
    codigo_ciudad: 70742,
    nombre_ciudad: "SAN LUIS DE SINCE",
    codigo_departamento: 70,
  },
  { codigo_ciudad: 70771, nombre_ciudad: "SUCRE", codigo_departamento: 70 },
  {
    codigo_ciudad: 70820,
    nombre_ciudad: "SANTIAGO DE TOLU",
    codigo_departamento: 70,
  },
  {
    codigo_ciudad: 70823,
    nombre_ciudad: "SAN JOSE DE TOLUVIEJO",
    codigo_departamento: 70,
  },
  { codigo_ciudad: 73001, nombre_ciudad: "IBAGUE", codigo_departamento: 73 },
  { codigo_ciudad: 73024, nombre_ciudad: "ALPUJARRA", codigo_departamento: 73 },
  { codigo_ciudad: 73026, nombre_ciudad: "ALVARADO", codigo_departamento: 73 },
  { codigo_ciudad: 73030, nombre_ciudad: "AMBALEMA", codigo_departamento: 73 },
  {
    codigo_ciudad: 73043,
    nombre_ciudad: "ANZOATEGUI",
    codigo_departamento: 73,
  },
  { codigo_ciudad: 73055, nombre_ciudad: "ARMERO", codigo_departamento: 73 },
  { codigo_ciudad: 73067, nombre_ciudad: "ATACO", codigo_departamento: 73 },
  { codigo_ciudad: 73124, nombre_ciudad: "CAJAMARCA", codigo_departamento: 73 },
  {
    codigo_ciudad: 73148,
    nombre_ciudad: "CARMEN DE APICALA",
    codigo_departamento: 73,
  },
  {
    codigo_ciudad: 73152,
    nombre_ciudad: "CASABIANCA",
    codigo_departamento: 73,
  },
  { codigo_ciudad: 73168, nombre_ciudad: "CHAPARRAL", codigo_departamento: 73 },
  { codigo_ciudad: 73200, nombre_ciudad: "COELLO", codigo_departamento: 73 },
  { codigo_ciudad: 73217, nombre_ciudad: "COYAIMA", codigo_departamento: 73 },
  { codigo_ciudad: 73226, nombre_ciudad: "CUNDAY", codigo_departamento: 73 },
  { codigo_ciudad: 73236, nombre_ciudad: "DOLORES", codigo_departamento: 73 },
  { codigo_ciudad: 73268, nombre_ciudad: "ESPINAL", codigo_departamento: 73 },
  { codigo_ciudad: 73270, nombre_ciudad: "FALAN", codigo_departamento: 73 },
  { codigo_ciudad: 73275, nombre_ciudad: "FLANDES", codigo_departamento: 73 },
  { codigo_ciudad: 73283, nombre_ciudad: "FRESNO", codigo_departamento: 73 },
  { codigo_ciudad: 73319, nombre_ciudad: "GUAMO", codigo_departamento: 73 },
  { codigo_ciudad: 73347, nombre_ciudad: "HERVEO", codigo_departamento: 73 },
  { codigo_ciudad: 73349, nombre_ciudad: "HONDA", codigo_departamento: 73 },
  { codigo_ciudad: 73352, nombre_ciudad: "ICONONZO", codigo_departamento: 73 },
  { codigo_ciudad: 73408, nombre_ciudad: "LERIDA", codigo_departamento: 73 },
  { codigo_ciudad: 73411, nombre_ciudad: "LIBANO", codigo_departamento: 73 },
  {
    codigo_ciudad: 73443,
    nombre_ciudad: "SAN SEBASTIAN DE MARIQUITA",
    codigo_departamento: 73,
  },
  { codigo_ciudad: 73449, nombre_ciudad: "MELGAR", codigo_departamento: 73 },
  { codigo_ciudad: 73461, nombre_ciudad: "MURILLO", codigo_departamento: 73 },
  { codigo_ciudad: 73483, nombre_ciudad: "NATAGAIMA", codigo_departamento: 73 },
  { codigo_ciudad: 73504, nombre_ciudad: "ORTEGA", codigo_departamento: 73 },
  {
    codigo_ciudad: 73520,
    nombre_ciudad: "PALOCABILDO",
    codigo_departamento: 73,
  },
  { codigo_ciudad: 73547, nombre_ciudad: "PIEDRAS", codigo_departamento: 73 },
  { codigo_ciudad: 73555, nombre_ciudad: "PLANADAS", codigo_departamento: 73 },
  { codigo_ciudad: 73563, nombre_ciudad: "PRADO", codigo_departamento: 73 },
  {
    codigo_ciudad: 73585,
    nombre_ciudad: "PURIFICACION",
    codigo_departamento: 73,
  },
  { codigo_ciudad: 73616, nombre_ciudad: "RIOBLANCO", codigo_departamento: 73 },
  {
    codigo_ciudad: 73622,
    nombre_ciudad: "RONCESVALLES",
    codigo_departamento: 73,
  },
  { codigo_ciudad: 73624, nombre_ciudad: "ROVIRA", codigo_departamento: 73 },
  { codigo_ciudad: 73671, nombre_ciudad: "SALDAÑA", codigo_departamento: 73 },
  {
    codigo_ciudad: 73675,
    nombre_ciudad: "SAN ANTONIO",
    codigo_departamento: 73,
  },
  { codigo_ciudad: 73678, nombre_ciudad: "SAN LUIS", codigo_departamento: 73 },
  {
    codigo_ciudad: 73686,
    nombre_ciudad: "SANTA ISABEL",
    codigo_departamento: 73,
  },
  { codigo_ciudad: 73770, nombre_ciudad: "SUAREZ", codigo_departamento: 73 },
  {
    codigo_ciudad: 73854,
    nombre_ciudad: "VALLE DE SAN JUAN",
    codigo_departamento: 73,
  },
  { codigo_ciudad: 73861, nombre_ciudad: "VENADILLO", codigo_departamento: 73 },
  {
    codigo_ciudad: 73870,
    nombre_ciudad: "VILLAHERMOSA",
    codigo_departamento: 73,
  },
  {
    codigo_ciudad: 73873,
    nombre_ciudad: "VILLARRICA",
    codigo_departamento: 73,
  },
  { codigo_ciudad: 76001, nombre_ciudad: "CALI", codigo_departamento: 76 },
  { codigo_ciudad: 76020, nombre_ciudad: "ALCALA", codigo_departamento: 76 },
  { codigo_ciudad: 76036, nombre_ciudad: "ANDALUCIA", codigo_departamento: 76 },
  {
    codigo_ciudad: 76041,
    nombre_ciudad: "ANSERMANUEVO",
    codigo_departamento: 76,
  },
  { codigo_ciudad: 76054, nombre_ciudad: "ARGELIA", codigo_departamento: 76 },
  { codigo_ciudad: 76100, nombre_ciudad: "BOLIVAR", codigo_departamento: 76 },
  {
    codigo_ciudad: 76109,
    nombre_ciudad: "BUENAVENTURA",
    codigo_departamento: 76,
  },
  {
    codigo_ciudad: 76111,
    nombre_ciudad: "GUADALAJARA DE BUGA",
    codigo_departamento: 76,
  },
  {
    codigo_ciudad: 76113,
    nombre_ciudad: "BUGALAGRANDE",
    codigo_departamento: 76,
  },
  {
    codigo_ciudad: 76122,
    nombre_ciudad: "CAICEDONIA",
    codigo_departamento: 76,
  },
  { codigo_ciudad: 76126, nombre_ciudad: "CALIMA", codigo_departamento: 76 },
  {
    codigo_ciudad: 76130,
    nombre_ciudad: "CANDELARIA",
    codigo_departamento: 76,
  },
  { codigo_ciudad: 76147, nombre_ciudad: "CARTAGO", codigo_departamento: 76 },
  { codigo_ciudad: 76233, nombre_ciudad: "DAGUA", codigo_departamento: 76 },
  { codigo_ciudad: 76243, nombre_ciudad: "EL AGUILA", codigo_departamento: 76 },
  { codigo_ciudad: 76246, nombre_ciudad: "EL CAIRO", codigo_departamento: 76 },
  {
    codigo_ciudad: 76248,
    nombre_ciudad: "EL CERRITO",
    codigo_departamento: 76,
  },
  { codigo_ciudad: 76250, nombre_ciudad: "EL DOVIO", codigo_departamento: 76 },
  { codigo_ciudad: 76275, nombre_ciudad: "FLORIDA", codigo_departamento: 76 },
  { codigo_ciudad: 76306, nombre_ciudad: "GINEBRA", codigo_departamento: 76 },
  { codigo_ciudad: 76318, nombre_ciudad: "GUACARI", codigo_departamento: 76 },
  { codigo_ciudad: 76364, nombre_ciudad: "JAMUNDI", codigo_departamento: 76 },
  { codigo_ciudad: 76377, nombre_ciudad: "LA CUMBRE", codigo_departamento: 76 },
  { codigo_ciudad: 76400, nombre_ciudad: "LA UNION", codigo_departamento: 76 },
  {
    codigo_ciudad: 76403,
    nombre_ciudad: "LA VICTORIA",
    codigo_departamento: 76,
  },
  { codigo_ciudad: 76497, nombre_ciudad: "OBANDO", codigo_departamento: 76 },
  { codigo_ciudad: 76520, nombre_ciudad: "PALMIRA", codigo_departamento: 76 },
  { codigo_ciudad: 76563, nombre_ciudad: "PRADERA", codigo_departamento: 76 },
  { codigo_ciudad: 76606, nombre_ciudad: "RESTREPO", codigo_departamento: 76 },
  { codigo_ciudad: 76616, nombre_ciudad: "RIOFRIO", codigo_departamento: 76 },
  {
    codigo_ciudad: 76622,
    nombre_ciudad: "ROLDANILLO",
    codigo_departamento: 76,
  },
  { codigo_ciudad: 76670, nombre_ciudad: "SAN PEDRO", codigo_departamento: 76 },
  { codigo_ciudad: 76736, nombre_ciudad: "SEVILLA", codigo_departamento: 76 },
  { codigo_ciudad: 76823, nombre_ciudad: "TORO", codigo_departamento: 76 },
  { codigo_ciudad: 76828, nombre_ciudad: "TRUJILLO", codigo_departamento: 76 },
  { codigo_ciudad: 76834, nombre_ciudad: "TULUA", codigo_departamento: 76 },
  { codigo_ciudad: 76845, nombre_ciudad: "ULLOA", codigo_departamento: 76 },
  { codigo_ciudad: 76863, nombre_ciudad: "VERSALLES", codigo_departamento: 76 },
  { codigo_ciudad: 76869, nombre_ciudad: "VIJES", codigo_departamento: 76 },
  { codigo_ciudad: 76890, nombre_ciudad: "YOTOCO", codigo_departamento: 76 },
  { codigo_ciudad: 76892, nombre_ciudad: "YUMBO", codigo_departamento: 76 },
  { codigo_ciudad: 76895, nombre_ciudad: "ZARZAL", codigo_departamento: 76 },
  { codigo_ciudad: 81001, nombre_ciudad: "ARAUCA", codigo_departamento: 81 },
  { codigo_ciudad: 81065, nombre_ciudad: "ARAUQUITA", codigo_departamento: 81 },
  {
    codigo_ciudad: 81220,
    nombre_ciudad: "CRAVO NORTE",
    codigo_departamento: 81,
  },
  { codigo_ciudad: 81300, nombre_ciudad: "FORTUL", codigo_departamento: 81 },
  {
    codigo_ciudad: 81591,
    nombre_ciudad: "PUERTO RONDON",
    codigo_departamento: 81,
  },
  { codigo_ciudad: 81736, nombre_ciudad: "SARAVENA", codigo_departamento: 81 },
  { codigo_ciudad: 81794, nombre_ciudad: "TAME", codigo_departamento: 81 },
  { codigo_ciudad: 85001, nombre_ciudad: "YOPAL", codigo_departamento: 85 },
  { codigo_ciudad: 85010, nombre_ciudad: "AGUAZUL", codigo_departamento: 85 },
  { codigo_ciudad: 85015, nombre_ciudad: "CHAMEZA", codigo_departamento: 85 },
  {
    codigo_ciudad: 85125,
    nombre_ciudad: "HATO COROZAL",
    codigo_departamento: 85,
  },
  { codigo_ciudad: 85136, nombre_ciudad: "LA SALINA", codigo_departamento: 85 },
  { codigo_ciudad: 85139, nombre_ciudad: "MANI", codigo_departamento: 85 },
  { codigo_ciudad: 85162, nombre_ciudad: "MONTERREY", codigo_departamento: 85 },
  { codigo_ciudad: 85225, nombre_ciudad: "NUNCHIA", codigo_departamento: 85 },
  { codigo_ciudad: 85230, nombre_ciudad: "OROCUE", codigo_departamento: 85 },
  {
    codigo_ciudad: 85250,
    nombre_ciudad: "PAZ DE ARIPORO",
    codigo_departamento: 85,
  },
  { codigo_ciudad: 85263, nombre_ciudad: "PORE", codigo_departamento: 85 },
  { codigo_ciudad: 85279, nombre_ciudad: "RECETOR", codigo_departamento: 85 },
  {
    codigo_ciudad: 85300,
    nombre_ciudad: "SABANALARGA",
    codigo_departamento: 85,
  },
  { codigo_ciudad: 85315, nombre_ciudad: "SACAMA", codigo_departamento: 85 },
  {
    codigo_ciudad: 85325,
    nombre_ciudad: "SAN LUIS DE PALENQUE",
    codigo_departamento: 85,
  },
  { codigo_ciudad: 85400, nombre_ciudad: "TAMARA", codigo_departamento: 85 },
  { codigo_ciudad: 85410, nombre_ciudad: "TAURAMENA", codigo_departamento: 85 },
  { codigo_ciudad: 85430, nombre_ciudad: "TRINIDAD", codigo_departamento: 85 },
  {
    codigo_ciudad: 85440,
    nombre_ciudad: "VILLANUEVA",
    codigo_departamento: 85,
  },
  { codigo_ciudad: 86001, nombre_ciudad: "MOCOA", codigo_departamento: 86 },
  { codigo_ciudad: 86219, nombre_ciudad: "COLON", codigo_departamento: 86 },
  { codigo_ciudad: 86320, nombre_ciudad: "ORITO", codigo_departamento: 86 },
  {
    codigo_ciudad: 86568,
    nombre_ciudad: "PUERTO ASIS",
    codigo_departamento: 86,
  },
  {
    codigo_ciudad: 86569,
    nombre_ciudad: "PUERTO CAICEDO",
    codigo_departamento: 86,
  },
  {
    codigo_ciudad: 86571,
    nombre_ciudad: "PUERTO GUZMAN",
    codigo_departamento: 86,
  },
  {
    codigo_ciudad: 86573,
    nombre_ciudad: "PUERTO LEGUIZAMO",
    codigo_departamento: 86,
  },
  { codigo_ciudad: 86749, nombre_ciudad: "SIBUNDOY", codigo_departamento: 86 },
  {
    codigo_ciudad: 86755,
    nombre_ciudad: "SAN FRANCISCO",
    codigo_departamento: 86,
  },
  {
    codigo_ciudad: 86757,
    nombre_ciudad: "SAN MIGUEL",
    codigo_departamento: 86,
  },
  { codigo_ciudad: 86760, nombre_ciudad: "SANTIAGO", codigo_departamento: 86 },
  {
    codigo_ciudad: 86865,
    nombre_ciudad: "VALLE DEL GUAMUEZ",
    codigo_departamento: 86,
  },
  {
    codigo_ciudad: 86885,
    nombre_ciudad: "VILLAGARZON",
    codigo_departamento: 86,
  },
  {
    codigo_ciudad: 88001,
    nombre_ciudad: "SAN ANDRES",
    codigo_departamento: 88,
  },
  {
    codigo_ciudad: 88564,
    nombre_ciudad: "PROVIDENCIA",
    codigo_departamento: 88,
  },
  { codigo_ciudad: 91001, nombre_ciudad: "LETICIA", codigo_departamento: 91 },
  {
    codigo_ciudad: 91263,
    nombre_ciudad: "EL ENCANTO",
    codigo_departamento: 91,
  },
  {
    codigo_ciudad: 91405,
    nombre_ciudad: "LA CHORRERA",
    codigo_departamento: 91,
  },
  {
    codigo_ciudad: 91407,
    nombre_ciudad: "LA PEDRERA",
    codigo_departamento: 91,
  },
  {
    codigo_ciudad: 91430,
    nombre_ciudad: "LA VICTORIA",
    codigo_departamento: 91,
  },
  {
    codigo_ciudad: 91460,
    nombre_ciudad: "MIRITI - PARANA",
    codigo_departamento: 91,
  },
  {
    codigo_ciudad: 91530,
    nombre_ciudad: "PUERTO ALEGRIA",
    codigo_departamento: 91,
  },
  {
    codigo_ciudad: 91536,
    nombre_ciudad: "PUERTO ARICA",
    codigo_departamento: 91,
  },
  {
    codigo_ciudad: 91540,
    nombre_ciudad: "PUERTO NARIÑO",
    codigo_departamento: 91,
  },
  {
    codigo_ciudad: 91669,
    nombre_ciudad: "PUERTO SANTANDER",
    codigo_departamento: 91,
  },
  { codigo_ciudad: 91798, nombre_ciudad: "TARAPACA", codigo_departamento: 91 },
  { codigo_ciudad: 94001, nombre_ciudad: "INIRIDA", codigo_departamento: 94 },
  {
    codigo_ciudad: 94343,
    nombre_ciudad: "BARRANCOMINAS",
    codigo_departamento: 94,
  },
  {
    codigo_ciudad: 94883,
    nombre_ciudad: "SAN FELIPE",
    codigo_departamento: 94,
  },
  {
    codigo_ciudad: 94884,
    nombre_ciudad: "PUERTO COLOMBIA",
    codigo_departamento: 94,
  },
  {
    codigo_ciudad: 94885,
    nombre_ciudad: "LA GUADALUPE",
    codigo_departamento: 94,
  },
  { codigo_ciudad: 94886, nombre_ciudad: "CACAHUAL", codigo_departamento: 94 },
  { codigo_ciudad: 94887, nombre_ciudad: "PANA PANA", codigo_departamento: 94 },
  { codigo_ciudad: 94888, nombre_ciudad: "MORICHAL", codigo_departamento: 94 },
  {
    codigo_ciudad: 95001,
    nombre_ciudad: "SAN JOSE DEL GUAVIARE",
    codigo_departamento: 95,
  },
  { codigo_ciudad: 95015, nombre_ciudad: "CALAMAR", codigo_departamento: 95 },
  {
    codigo_ciudad: 95025,
    nombre_ciudad: "EL RETORNO",
    codigo_departamento: 95,
  },
  {
    codigo_ciudad: 95200,
    nombre_ciudad: "MIRAFLORES",
    codigo_departamento: 95,
  },
  { codigo_ciudad: 97001, nombre_ciudad: "MITU", codigo_departamento: 97 },
  { codigo_ciudad: 97161, nombre_ciudad: "CARURU", codigo_departamento: 97 },
  { codigo_ciudad: 97511, nombre_ciudad: "PACOA", codigo_departamento: 97 },
  { codigo_ciudad: 97666, nombre_ciudad: "TARAIRA", codigo_departamento: 97 },
  { codigo_ciudad: 97777, nombre_ciudad: "PAPUNAHUA", codigo_departamento: 97 },
  { codigo_ciudad: 97889, nombre_ciudad: "YAVARATE", codigo_departamento: 97 },
  {
    codigo_ciudad: 99001,
    nombre_ciudad: "PUERTO CARREÑO",
    codigo_departamento: 99,
  },
  {
    codigo_ciudad: 99524,
    nombre_ciudad: "LA PRIMAVERA",
    codigo_departamento: 99,
  },
  {
    codigo_ciudad: 99624,
    nombre_ciudad: "SANTA ROSALIA",
    codigo_departamento: 99,
  },
  { codigo_ciudad: 99773, nombre_ciudad: "CUMARIBO", codigo_departamento: 99 },
];
